#!/usr/bin/env python3
"""foldgate_engine — minor-allele folding of a two-site frequency spectrum, and
exact deciders that place a folded spectrum inside or outside the folded image of
the variable-population-size Kingman class.

Register: EXACT. The folding map, every rank, every convex or conic weight, every
witness margin and every polynomial nonnegativity certificate is decided in
fractions.Fraction / sympy Rational arithmetic. Floats appear in two roles only:
as PROPOSERS inside the hunts (scipy's HiGHS linear programs on float grids; a
proposal that fails exact reconstruction or exact certification is discarded,
never reported) and as display copies (`*_float` fields beside the exact field
they copy). Nothing here is an interval enclosure; do not mix this register with
ball arithmetic. The folding map, the exact verifiers (solve_exact,
bern_1d_nonneg) and the reference loaders need the standard library only; the
hunts import numpy, scipy and sympy on first call.

The folding map
---------------
Two fully linked segregating sites in a sample of n haploid sequences carry
derived-allele counts i and j (1 <= i, j <= n-1). Their expected joint spectrum,
normalized to unit mass, is a symmetric (n-1) x (n-1) table q_ij, stored here on
symmetric coordinates (i <= j) as a dict {(i, j): value}; the pooled-pair mass
convention is  sum_{i<=j} (2 - [i=j]) q_ij = 1  (full_sum). Without the ancestral
state at either site only minor-allele counts are observable, so cell (i, j) is
indistinguishable from (i, n-j), (n-i, j) and (n-i, n-j). With minor classes
C_a = {a, n-a}, a = 1..m, m = floor(n/2), the folded spectrum is

    Phi(q)_ab = sum_{x in C_a} sum_{y in C_b} q_xy,     1 <= a <= b <= m,

acting on the full table; on stored symmetric coordinates it is the induced
surjection onto folded symmetric coordinates (a <= b). The class SETS handle the
self-conjugate class a = n-a at even n with no double count, and mass is preserved:
sum_{a<=b} (2 - [a=b]) Phi(q)_ab = 1. This is the two-site analog of folding the
single-site spectrum, eta_i = (xi_i + xi_{n-i}) / (1 + [i = n-i]) (Fu 1995).

  fold_coeffs(n)    -> {(a,b): {(i,j): int}}  the map itself (integer weights)
  apply_fold(n, M)  -> {(a,b): value}  Phi applied to a dict M[(i,j)], i <= j, of
                       Fractions (or of anything closed under + and * by a
                       Fraction, e.g. sympy expressions: folding acts entrywise
                       on polynomial ingredients too)
  pullback(n, v)    -> {(i,j): Fraction}  W = Phi^T v, so <v, Phi x> == <Phi^T v, x>
                       exactly for every x (the identity the witnesses rely on)
  exact_rank(rows)  -> int   rank of Fraction row vectors by Gaussian elimination
  rank_report(n)    -> dict  exact ranks of Phi in stored-symmetric and in full
                       (n-1)^2 -> m^2 form and the kernel dimension; Phi is onto:
                       n = 4: 6 -> 3 (kernel 3); n = 5: 10 -> 3 (kernel 7);
                       n = 6: 15 -> 6 (kernel 9)
  PAIRS(n), FPAIRS(n), mults(prs), full_sum(n, M)  coordinate lists, the
                       multiplicities 2 - [i=j], and the pooled mass sum.

Setting for the deciders
------------------------
For an exchangeable coalescent the expected two-site spectrum of two fully linked
sites is proportional to the second-moment matrix M_ij = E[L_i L_j] of the branch
lengths L_i subtending i leaves (two mutations dropped uniformly on one genealogy,
small-theta limit; Ferretti et al. 2018 treat the Kingman case, and the branch-
length moments of Lambda-coalescents are the objects of Birkner, Blath & Eldon
2013). q = M / full_sum(M) is scale free and phi = Phi(q) is what an unpolarized
data set estimates. make_object(n, M) packages a target as
{'n', 'M', 'tot', 'q', 'phi'}, the calling convention of every decider.

The comparison class is the Kingman coalescent under an ARBITRARY population-size
history, closed under per-locus pooling (convex mixtures over histories). Write a
history as a coalescence intensity R(tau) and level s(tau) = e^{-R(tau)}; branch
length subtending i leaves accrues as L_i = int N_i(g_{s(tau)}) dtau with N_i(g)
the number of size-i blocks of the Kingman n-coalescent at intensity g. Taking
expectations inside the double integral,

    E[L_i L_j] = int int Csym_ij(x, y) nu(dx) nu(dy),

where nu is the pushforward of dtau under s (a finite measure on (0,1]) and
Csym_ij(x, y) = E-sym[N_i(g_x) N_j(g_y)] is the exact two-time block-count kernel,
a polynomial with rational coefficients on the chart x = s, y = s*u,
(s, u) in [0,1]^2. Pooling adds such terms with positive weights, so the class
moments form a cone generated by the kernel. The extreme histories are single
atoms nu = D delta_t ("burst-freeze-crash": an instantaneous burst of coalescence
down to level t, a freeze of duration D during which all length accrues on the
constant partition, then instantaneous collapse); their second moments are the
diagonal m2_ij(t) = Csym_ij(t, t), a polynomial in t. These class polynomials are
INPUTS to this module ("ingredients", below); exact copies for n = 4, 5, 6 ship
under reference/foldgate/.

The deciders (exact certificates; verdict vocabulary in capitals)
----------------------------------------------------------------
  inside_hunt(n, phi, fcomps, tgrid) -> ([(t_k, lambda_k), ...], 'exact') | (None, status)
      ANNIHILATED. phi = sum_k lambda_k fcomps[k] exactly with rational
      lambda_k >= 0, sum 1, over the folded normalized single-atom components
      fcomps (folded_components) on the node list tgrid. Atom poolings lie in the
      closure of the class, so the folded target IS a point of the folded class
      closure and no folded functional of any kind separates it. An LP proposes
      the support; solve_exact reconstructs rational weights on square subsystems
      of the support and every coordinate is re-verified exactly. status is
      'lp_infeasible' when even the float LP finds no combination.
  witness_hunt(n, obj, kernF, kern, s, u) -> (witness, lp_delta0) | (None, lp_delta0)
      SURVIVES_OUT_FULLCLASS. A folded functional v (coordinates a <= b) whose
      pullback W = Phi^T v has kernel K_W(s,u) = sum_{i<=j} W_ij Csym_ij(s,u) >= 0
      on all of [0,1]^2, certified by exact tensor-Bernstein expansion with
      quadtree subdivision (bern_2d_nonneg), together with the exact margin
      <v, Phi(M)> < 0. For every history in the class <v, Phi(M')> =
      int int K_W dnu dnu >= 0, so the folded target lies outside the folded
      image of the ENTIRE class. kernF = fold_exprs(n, kern) is the folded kernel.
      The LP proposes v on a 33 x 17 grid at increasing margins eta; the returned
      dict carries v, W, the exact margin, its normalized form and the l1
      stand-off lower bound margin / max|v| (exact, with float display copies).
  outer_membership(n, obj, kernF, s, u) -> dict
      NO_LINEAR_WITNESS. Exact conic membership Phi(M) in cone{Phi(Csym(x, y))}
      over the dyadic 17-grid (generators '(x,y)', kernel evaluated at s = x,
      u = y/x, nonnegative rational weights). A nonnegative kernel pairs to >= 0
      with every generator, so this rules out EVERY witness of the witness_hunt
      type. It does NOT prove class membership (the target could still be
      separated by a functional whose kernel is not pointwise nonnegative), and it
      is reported as an obstruction, never as inside.
  diagonal_witness_hunt(n, obj, m2pF, s, tgrid) -> witness | None
      Weaker exclusion: v with diagonal pullback polynomial
      p_v(t) = sum_{a<=b} v_ab (Phi m2)_ab(t) >= 0 on [0,1] (exact 1-D Bernstein,
      bern_1d_nonneg) and <v, Phi(M)> < 0 exactly. The folded target then lies
      outside the folded hull of ALL poolings of single-atom histories, of any
      support; coupled multi-epoch histories are not excluded by this certificate.
      m2pF = fold_exprs(n, m2_sympy(ing, s)).
  realization_hunt_n4(obj, kern, s, u, budget_s=600) -> dict
      n = 4 only. Scans two-atom histories nu = c1 delta_x1 + c2 delta_x2 (x1 on a
      short rational list) for one whose folded normalized spectrum equals phi
      IDENTICALLY: resultant elimination, exact real-root isolation, exact
      back-substitution and verification of every folded coordinate. 'REALIZED'
      would prove membership outright; otherwise 'no_2atom_realization_found_on_scan'.
  decide(n, obj, fcomps, tgrid, kernF, kern, s, u) -> record
      The decision chain inside -> full-class witness -> conic obstruction for one
      target: verdict in {ANNIHILATED, SURVIVES_OUT_FULLCLASS, NO_LINEAR_WITNESS,
      UNDECIDED} with the certificate attached. Sanity law: a constant-size
      Kingman target is in the class and must never come out SURVIVES_OUT_FULLCLASS.
Exact building blocks, usable on their own: solve_exact (Fraction Gaussian
elimination on a square system, None if singular); bern_1d_nonneg(coeffs) and
bern_2d_nonneg(expr, s, u) (True = certified >= 0 on [0,1] / [0,1]^2 by
Bernstein coefficients with dyadic subdivision, False = an exact negative value
was found, None = inconclusive at the depth cap; a polynomial that touches zero
in the interior is typically inconclusive, not certified); poly_coeffs_2d. The
convex-hull and subdivision properties of the Bernstein basis that make the
certificate sound are classical (Farouki 2012).

Ingredients and reference data (reference/foldgate/)
----------------------------------------------------
  kingman_class_polys_n456.json  for n = 4, 5, 6: the diagonal polynomials
      m2_ij(t) ({exponent: coefficient}, exponents are binomial numbers C(k,2))
      and the two-time kernel Csym_ij(s,u) ({'es,eu': coefficient}), all exact
      rationals. load_ingredients(n) reads them as Fractions;
      component_q(n, ing, t) evaluates the normalized single-atom component at a
      rational level t (t = 0 is the directional limit t -> 0+, the last-two-
      lineages term); folded_components(n, ing, tgrid) folds them on a node list
      (tgrid_of() is the dyadic 83-node list used for the reference table);
      m2_sympy(ing, s) and kernel_sympy(ing) -> (kern, (s, u)) give sympy forms and
      fold_exprs(n, polys) folds a dict of expressions. Any exact engine that
      produces E[L_i L_j] of a target and the class polynomials in this format
      extends the deciders to other n; in this package that engine is the exact
      two-site moment engine (twosfs_engine: lambda_moments(n, lam_of(family,
      param)) for a target under any Lambda-coalescent, component_moments and
      twotime_kernel_poly for the class; twosfs_certificates.m2_polys for the
      diagonal polynomials), whose outputs at n = 4, 5, 6 are exactly the
      shipped files.
  folded_reference_n456.json  sixteen targets at n = 4, 5, 6: Beta(2-alpha, alpha)
      coalescents (alpha in {1/2, 1, 3/2} at n = 4, {3/2, 19/10} at n = 5,
      {19/10, 7/4} at n = 6), Dirac (psi-) coalescents (psi in {1/4, 2/5}, {1/4,
      1/10}, {1/20, 3/40}) and the constant-size Kingman coalescent at each n, each
      with its exact M = E[L_i L_j], its folded normalized spectrum and the exact
      certificate the deciders returned: ten ANNIHILATED (every n = 4 and n = 5
      row except Beta(1/2) at n = 4, all with 3-node supports, the Kingman
      sanity rows at n = 4 and n = 5 among them), six NO_LINEAR_WITNESS
      (Beta(1/2) at n = 4 and all five n = 6 rows, each with an exact conic
      certificate AND an exact diagonal witness with normalized margins between
      6.6e-3 and 1.1e-2), SURVIVES_OUT_FULLCLASS zero times; the two-atom
      realization scan at n = 4, alpha = 1/2 is negative; plus the rank table.
      load_reference_rows() reads it; make_object(n, row['M']) rebuilds a target.
      lam_of(family, param) maps a row label to the merger-rate function of
      lambda_exact (popcorn.lambda_coalescent) for use with a moment engine.
  In words: at these sample sizes minor-allele folding maps every tested
  multiple-merger spectrum either exactly into the folded Kingman-class closure or
  to a point that no pointwise-nonnegative kernel functional separates from it,
  while the weaker single-atom-pooling hull still excludes the n = 6 targets and
  Beta(1/2) at n = 4 (and, at n = 6, even the constant-size Kingman target, a
  single smooth history rather than a pooling of atoms: a reminder that the
  diagonal certificate excludes atom poolings only).

Cost: the folding map and the exact verifications are instantaneous; rebuilding
all sixteen reference decisions from the shipped ingredients (CLI below) takes
seconds single-threaded, dominated by sympy substitutions in outer_membership
and, when a proposal must be certified, by bern_2d_nonneg, whose subdivision cost
grows with the kernel degree (total degree 12, 20, 30 at n = 4, 5, 6). Cap BLAS
threads (OMP_NUM_THREADS=1 or a few) for the LP proposers; nothing here benefits
from more.

Scope: fully linked sites (no recombination between the two sites), expected
spectra (first moments of the two-site spectrum = second moments of branch
lengths), haploid sample counts, minor-allele folding applied independently at
each site; class ingredients shipped for n = 4, 5, 6 only; realization scan at
n = 4 only. The deciders certify statements about the folded IMAGE of a model
class; they are not estimators and say nothing about sampling noise.

CLI:  python3 foldgate_engine.py [--n {4,5,6}] [--out FILE]
  rebuilds the folded components and folded kernel from the shipped ingredients,
  runs decide() (and diagonal_witness_hunt on obstruction rows) for every
  reference target at the chosen n (default: all), prints one line per target
  with the live verdict beside the reference verdict, exits 1 on any verdict
  mismatch or sanity-law violation, and writes the records to FILE only with
  --out. Needs numpy, scipy and sympy.

References
  Fu, Y.-X. (1995). Statistical properties of segregating sites. Theor. Popul.
    Biol. 48, 172-197.
  Ferretti, L., Klassmann, A., Raineri, E., Ramos-Onsins, S. E., Wiehe, T. &
    Achaz, G. (2018). The neutral frequency spectrum of linked sites. Theor.
    Popul. Biol. 123, 70-79.
  Birkner, M., Blath, J. & Eldon, B. (2013). Statistical properties of the
    site-frequency spectrum associated with Lambda-coalescents. Genetics 195,
    1037-1053.
  Farouki, R. T. (2012). The Bernstein polynomial basis: a centennial
    retrospective. Comput. Aided Geom. Des. 29, 379-419.
"""
import argparse
import json
import os
import sys
import time
from fractions import Fraction as F
from math import comb
from itertools import combinations

HERE = os.path.dirname(os.path.abspath(__file__))
REFERENCE_DIR = os.path.join(HERE, 'reference', 'foldgate')
ROWS_REF = os.path.join(REFERENCE_DIR, 'folded_reference_n456.json')
INGREDIENTS_REF = os.path.join(REFERENCE_DIR, 'kingman_class_polys_n456.json')

PAIRS = lambda n: [(i, j) for i in range(1, n) for j in range(i, n)]
FPAIRS = lambda n: [(a, b) for a in range(1, n // 2 + 1)
                    for b in range(a, n // 2 + 1)]

# ------------------------------------------------------------ the folding map

def fold_coeffs(n):
    """Phi on stored symmetric coords: {(a,b): {(i,j): int}}, a<=b, i<=j.

    phi_ab = sum_{x in C_a, y in C_b} qmat_xy with qmat_xy = q[(min,max)];
    the class sets C_a = {a, n-a} handle the fixed class a = n-a (even n)
    with no double count."""
    m = n // 2
    cls = {a: sorted({a, n - a}) for a in range(1, m + 1)}
    Phi = {}
    for a, b in FPAIRS(n):
        co = {}
        for x in cls[a]:
            for y in cls[b]:
                k = (min(x, y), max(x, y))
                co[k] = co.get(k, 0) + 1
        Phi[(a, b)] = co
    return Phi

def apply_fold(n, M):
    Phi = fold_coeffs(n)
    return {fp: sum(F(c) * M[ij] for ij, c in co.items())
            for fp, co in Phi.items()}

def pullback(n, v):
    """W = Phi^T v on stored unfolded coords."""
    Phi = fold_coeffs(n)
    W = {ij: F(0) for ij in PAIRS(n)}
    for fp, co in Phi.items():
        for ij, c in co.items():
            W[ij] += F(c) * v[fp]
    return W

def exact_rank(rows):
    """Rank of a list of Fraction row-vectors by Gaussian elimination."""
    M = [list(map(F, r)) for r in rows]
    rank, ncol = 0, (len(M[0]) if M else 0)
    for c in range(ncol):
        piv = next((r for r in range(rank, len(M)) if M[r][c] != 0), None)
        if piv is None:
            continue
        M[rank], M[piv] = M[piv], M[rank]
        pv = M[rank][c]
        M[rank] = [x / pv for x in M[rank]]
        for r in range(len(M)):
            if r != rank and M[r][c] != 0:
                f = M[r][c]
                M[r] = [x - f * y for x, y in zip(M[r], M[rank])]
        rank += 1
    return rank

def rank_report(n):
    prs, fps = PAIRS(n), FPAIRS(n)
    Phi = fold_coeffs(n)
    sym_rows = [[F(Phi[fp].get(ij, 0)) for ij in prs] for fp in fps]
    # full (n-1)^2 -> m^2 orbit-sum map
    m = n // 2
    cls = {a: sorted({a, n - a}) for a in range(1, m + 1)}
    cells = [(i, j) for i in range(1, n) for j in range(1, n)]
    fcells = [(a, b) for a in range(1, m + 1) for b in range(1, m + 1)]
    full_rows = [[F(1) if (i in cls[a] and j in cls[b]) else F(0)
                  for (i, j) in cells] for (a, b) in fcells]
    return {'n': n, 'dim_unfolded_sym': len(prs), 'dim_folded_sym': len(fps),
            'rank_sym': exact_rank(sym_rows),
            'dim_unfolded_full': (n - 1) ** 2, 'dim_folded_full': m * m,
            'rank_full': exact_rank(full_rows),
            'kernel_dim_sym': len(prs) - exact_rank(sym_rows)}

# ------------------------------------------------------------ helpers

def mults(prs):
    return {ij: (1 if ij[0] == ij[1] else 2) for ij in prs}

def full_sum(n, M, prs=None):
    prs = prs or PAIRS(n)
    return sum((1 if i == j else 2) * M[(i, j)] for i, j in prs)

def lam_of(fam, param):
    from lambda_exact import beta_rate, dirac_rate, kingman_rate
    if fam == 'kingman':
        return kingman_rate()
    return beta_rate(F(param)) if fam == 'beta' else dirac_rate(F(param))

def tgrid_of():
    tg = [F(a, 64) for a in range(65)] + \
         [F(1) - F(1, 1 << k) for k in range(7, 16)] + \
         [F(1, 1 << k) for k in range(7, 16)]
    return sorted(set(tg))

# ------------------------------------------- exact linear algebra and Bernstein certificates

def solve_exact(Amat, bvec):
    """Gaussian elimination, Fractions. Returns x or None if singular."""
    m = len(Amat)
    M = [row[:] + [bvec[r]] for r, row in enumerate(Amat)]
    for c in range(m):
        piv = next((r for r in range(c, m) if M[r][c] != 0), None)
        if piv is None:
            return None
        M[c], M[piv] = M[piv], M[c]
        pv = M[c][c]
        M[c] = [x / pv for x in M[c]]
        for r in range(m):
            if r != c and M[r][c] != 0:
                f = M[r][c]
                M[r] = [x - f * y for x, y in zip(M[r], M[c])]
    return [M[r][m] for r in range(m)]

def poly_coeffs_2d(expr, s_, u_):
    import sympy as sp
    p = sp.Poly(expr, s_, u_)
    d = {}
    for (a, b), c in p.terms():
        d[(a, b)] = F(int(sp.numer(c)), int(sp.denom(c)))
    return d

def bern_1d_nonneg(coeffs, depth=0, max_depth=12, lo=F(0), hi=F(1)):
    """coeffs: {deg: Fraction} of poly on [lo,hi] mapped to [0,1]. True if
    certified >= 0 on the interval (exact), False if a definite negative
    value found, None if inconclusive at max depth."""
    m = max(coeffs) if coeffs else 0
    c = [coeffs.get(a, F(0)) for a in range(m + 1)]
    b = [sum(F(comb(k, a), comb(m, a)) * c[a] for a in range(k + 1))
         for k in range(m + 1)]
    if all(x >= 0 for x in b):
        return True
    # definite negativity test at endpoints / midpoint
    def ev(x):
        return sum(cc * x ** a for a, cc in enumerate(c))
    for x in (F(0), F(1, 2), F(1)):
        if ev(x) < 0:
            return False
    if depth >= max_depth:
        return None
    # subdivide: left half p(x/2), right half p(1/2 + x/2)
    for half in (0, 1):
        sub = {}
        for a, cc in enumerate(c):
            if cc == 0:
                continue
            # substitute x = (half + y)/2, expand binomially
            for k in range(a + 1):
                sub[k] = sub.get(k, F(0)) + cc * F(comb(a, k), 2 ** a) * \
                    (F(half) ** (a - k) if a - k >= 0 else F(0))
        r = bern_1d_nonneg(sub, depth + 1, max_depth)
        if r is not True:
            return r
    return True

def bern_2d_nonneg(expr, s_, u_, max_depth=7):
    """Exact certificate expr >= 0 on [0,1]^2 via tensor Bernstein +
    quadtree subdivision (subdivision by exact sympy substitution)."""
    import sympy as sp
    def rec(e, depth):
        cf = poly_coeffs_2d(e, s_, u_)
        if not cf:
            return True
        ms = max(a for a, _ in cf)
        mu = max(b for _, b in cf)
        C = [[cf.get((a, b), F(0)) for b in range(mu + 1)]
             for a in range(ms + 1)]
        ok = True
        for k in range(ms + 1):
            for l in range(mu + 1):
                bkl = sum(F(comb(k, a), comb(ms, a)) * F(comb(l, b), comb(mu, b))
                          * C[a][b] for a in range(k + 1) for b in range(l + 1))
                if bkl < 0:
                    ok = False
                    break
            if not ok:
                break
        if ok:
            return True
        # definite negativity probes
        for xs in (F(0), F(1, 2), F(1)):
            for xu in (F(0), F(1, 2), F(1)):
                v = sum(c * xs ** a * xu ** b for (a, b), c in cf.items())
                if v < 0:
                    return False
        if depth >= max_depth:
            return None
        for hs in (0, 1):
            for hu in (0, 1):
                e2 = sp.expand(e.subs({s_: (sp.Integer(hs) + s_) / 2,
                                       u_: (sp.Integer(hu) + u_) / 2}))
                r = rec(e2, depth + 1)
                if r is not True:
                    return r
        return True
    return rec(sp.expand(expr), 0)

# ------------------------------------------------------------ deciders

def inside_hunt(n, phiL, fcomps, tgrid):
    """Exact convex-combination membership of phiL in conv(folded comps)."""
    import numpy as np
    from scipy.optimize import linprog
    fps = FPAIRS(n)
    Aeq = np.array([[float(c[fp]) for c in fcomps] for fp in fps]
                   + [[1.0] * len(fcomps)])
    beq = np.array([float(phiL[fp]) for fp in fps] + [1.0])
    res = linprog(c=np.zeros(len(fcomps)), A_eq=Aeq, b_eq=beq,
                  bounds=[(0, None)] * len(fcomps), method='highs')
    if res.status != 0:
        return None, 'lp_infeasible'
    sup = sorted(range(len(fcomps)), key=lambda k: -res.x[k])[:10]
    sup = [k for k in sup if res.x[k] > 1e-13] or sup[:1]
    rowsA = [[fcomps[k][fp] for k in sup] for fp in fps] + [[F(1)] * len(sup)]
    rhs = [phiL[fp] for fp in fps] + [F(1)]
    nr = len(rowsA)
    for sz in range(1, min(len(sup), nr) + 1):
        for cols in combinations(range(len(sup)), sz):
            for ridx in combinations(range(nr), sz):
                A = [[rowsA[r][c] for c in cols] for r in ridx]
                b = [rhs[r] for r in ridx]
                s0 = solve_exact(A, b)
                if s0 is None or any(x < 0 for x in s0):
                    continue
                if all(sum(rowsA[r][c] * s0[k] for k, c in enumerate(cols))
                       == rhs[r] for r in range(nr)):
                    return ([(str(tgrid[sup[c]]), str(s0[k]))
                             for k, c in enumerate(cols)], 'exact')
    return None, 'float_feasible_exact_reconstruction_failed'

def witness_hunt(n, obj, kernF, kern, s_, u_, grid_ns=33, grid_nu=17):
    """Full-class folded witness: LP proposes v, exact 2-D Bernstein certifies
    the pullback kernel on [0,1]^2, the exact margin <v, Phi(M)> < 0 decides."""
    import numpy as np
    from scipy.optimize import linprog
    import sympy as sp
    fps = FPAIRS(n)
    d = len(fps)
    Kf = {fp: sp.lambdify((s_, u_), kernF[fp], 'numpy') for fp in fps}
    sg = np.linspace(0, 1, grid_ns)
    ug = np.linspace(0, 1, grid_nu)
    SS, UU = np.meshgrid(sg, ug, indexing='ij')
    vals, phi = {}, np.zeros(SS.shape)
    for fp in fps:
        v = np.asarray(Kf[fp](SS, UU), dtype=float) + 0 * SS
        vals[fp] = v
        phi += v * (1 if fp[0] == fp[1] else 2)
    phiL_norm = [float(obj['phi'][fp]) for fp in fps]
    pts_vals = [[vals[fp][a, b] for fp in fps]
                for a in range(SS.shape[0]) for b in range(SS.shape[1])]
    pts_phi = [phi[a, b] for a in range(SS.shape[0])
               for b in range(SS.shape[1])]
    lp0 = None
    for eta in (0.0, 1e-3, 3e-3, 1e-2):
        A_ub = [[-x for x in kv] + [0.0] for kv in pts_vals]
        b_ub = [-eta * kp for kp in pts_phi]
        A_ub.append(phiL_norm + [1.0])
        b_ub.append(0.0)
        res = linprog(c=[0.0] * d + [-1.0], A_ub=A_ub, b_ub=b_ub,
                      bounds=[(-1, 1)] * d + [(0, None)], method='highs')
        z = float(res.x[-1]) if res.status == 0 else None
        if eta == 0.0:
            lp0 = z
        if res.status != 0 or res.x[-1] <= 1e-8:
            break
        v = {fp: F(float(res.x[k])).limit_denominator(10 ** 6)
             for k, fp in enumerate(fps)}
        phiM = apply_fold(n, obj['M'])
        GM = sum(v[fp] * phiM[fp] for fp in fps)
        if GM >= 0:
            continue
        expr = sp.expand(sum(sp.Rational(v[fp].numerator, v[fp].denominator)
                             * kernF[fp] for fp in fps))
        cert = bern_2d_nonneg(expr, s_, u_)
        if cert is not True:
            continue
        # cross-check via the pullback route <Phi^T v, M> == <v, Phi(M)>
        W = pullback(n, v)
        GM2 = sum(W[ij] * obj['M'][ij] for ij in PAIRS(n))
        assert GM2 == GM
        vinf = max(abs(x) for x in v.values())
        return {'witness_v_folded': {f'{a},{b}': str(v[(a, b)])
                                     for a, b in fps},
                'pullback_W': {f'{i},{j}': str(W[(i, j)])
                               for i, j in PAIRS(n)},
                'G_phiM_exact': str(GM),
                'norm_margin_exact': str(-GM / obj['tot']),
                'norm_margin_float': float(-GM / obj['tot']),
                'standoff_l1_lb_exact': str(-GM / obj['tot'] / vinf),
                'standoff_l1_lb_float': float(-GM / obj['tot'] / vinf),
                'eta': eta, 'bernstein': 'certified',
                'lp_delta0': lp0}, lp0
    return None, lp0

def outer_membership(n, obj, kernF, s_, u_):
    """phi(M_Lambda) in cone{Phi(Csym(x,y))} on the dyadic 17-grid?"""
    import numpy as np
    from scipy.optimize import linprog
    import sympy as sp
    fps = FPAIRS(n)
    cols, labels = [], []
    for a in range(0, 17):
        for b in range(0, a + 1):
            x, y = F(a, 16), F(b, 16)
            col = {}
            for fp in fps:
                val = kernF[fp].subs({s_: sp.Rational(x),
                                      u_: sp.Rational(y / x) if x != 0 else 0})
                col[fp] = F(int(sp.numer(val)), int(sp.denom(val)))
            cols.append(col)
            labels.append(f'({a}/16,{b}/16)')
    phiM = apply_fold(n, obj['M'])
    Aeq = np.array([[float(c[fp]) for c in cols] for fp in fps])
    beq = np.array([float(phiM[fp]) for fp in fps])
    res = linprog(c=np.zeros(len(cols)), A_eq=Aeq, b_eq=beq,
                  bounds=[(0, None)] * len(cols), method='highs')
    if res.status != 0:
        return {'outer_lp': 'infeasible'}
    d = len(fps)
    sup = sorted(range(len(cols)), key=lambda k: -res.x[k])[:2 * d]
    tries = 0
    for S in combinations(sup, d):
        tries += 1
        if tries > 3000:
            break
        A = [[cols[k][fp] for k in S] for fp in fps]
        b = [phiM[fp] for fp in fps]
        s0 = solve_exact(A, b)
        if s0 is None or any(x < 0 for x in s0):
            continue
        return {'outer_lp': 'feasible',
                'outer_membership': {
                    'generators': [labels[k] for k in S],
                    'weights': [str(x) for x in s0],
                    'meaning': 'Phi(M_Lambda) in cone{Phi(Csym points)} '
                               'EXACTLY: no pointwise-nonneg folded kernel '
                               'witness exists (no full-class separation '
                               'by linear certificates of this type)'}}
    return {'outer_lp': 'feasible', 'outer_membership':
            'float_feasible_exact_open'}

def diagonal_witness_hunt(n, obj, m2pF, s_, tgrid_f):
    """LP proposes folded diagonal witness; 1-D Bernstein certifies."""
    import numpy as np
    from scipy.optimize import linprog
    import sympy as sp
    fps = FPAIRS(n)
    d = len(fps)
    funcs = {fp: sp.lambdify(s_, m2pF[fp], 'numpy') for fp in fps}
    tg = np.array([float(t) for t in tgrid_f])
    vals = {fp: np.asarray(funcs[fp](tg), dtype=float) + 0 * tg for fp in fps}
    phid = sum(v * (1 if fp[0] == fp[1] else 2) for fp, v in vals.items())
    phiL = [float(obj['phi'][fp]) for fp in fps]
    best = None
    for eta in (0.0, 1e-3, 3e-3, 1e-2):
        A_ub = [[-vals[fp][k] for fp in fps] + [0.0] for k in range(len(tg))]
        b_ub = [-eta * phid[k] for k in range(len(tg))]
        A_ub.append(phiL + [1.0])
        b_ub.append(0.0)
        res = linprog(c=[0.0] * d + [-1.0], A_ub=A_ub, b_ub=b_ub,
                      bounds=[(-1, 1)] * d + [(0, None)], method='highs')
        if res.status != 0 or res.x[-1] <= 1e-9:
            continue
        v = {fp: F(float(res.x[k])).limit_denominator(10 ** 6)
             for k, fp in enumerate(fps)}
        phiM = apply_fold(n, obj['M'])
        GM = sum(v[fp] * phiM[fp] for fp in fps)
        if GM >= 0:
            continue
        pexpr = sp.expand(sum(sp.Rational(v[fp].numerator, v[fp].denominator)
                              * m2pF[fp] for fp in fps))
        cf = {}
        for (a,), c in sp.Poly(pexpr, s_).terms():
            cf[a] = F(int(sp.numer(c)), int(sp.denom(c)))
        if bern_1d_nonneg(cf) is not True:
            continue
        vinf = max(abs(x) for x in v.values())
        best = {'witness_v_folded': {f'{a},{b}': str(v[(a, b)])
                                     for a, b in fps},
                'G_phiM_exact': str(GM),
                'norm_margin_exact': str(-GM / obj['tot']),
                'standoff_l1_lb_exact': str(-GM / obj['tot'] / vinf),
                'standoff_l1_lb_float': float(-GM / obj['tot'] / vinf),
                'eta': eta, 'bernstein_1d': 'certified',
                'meaning': 'folded point certifiably OUTSIDE the folded hull '
                           'of ALL single-atom (burst-freeze-crash) poolings, '
                           'any support'}
        break
    return best

def realization_hunt_n4(obj, kern, s_, u_, budget_s=600):
    """Two-atom product-history realization of a folded n=4 target (obj).

    Atoms x1 > x2 = x1*u, weights (1, r).  Fixing x1 rational leaves two
    polynomial equations in (u, r); eliminate r by resultant, isolate real
    roots exactly, back-substitute, verify all folded coordinates exactly."""
    import sympy as sp
    t0 = time.time()
    n = 4
    fps = FPAIRS(n)
    r_ = sp.Symbol('r', positive=True)
    Phi = fold_coeffs(n)
    # folded kernel entries as sympy in (s_, u_)
    kernF = {fp: sp.expand(sum(sp.Integer(c) * kern[ij]
                               for ij, c in co.items()))
             for fp, co in Phi.items()}
    # M(x1, u, r) folded: K(x1,x1): s=x1,u=1 ; K(x1,x2): s=x1,u=u ;
    # K(x2,x2): s=x1*u, u=1
    phiL = obj['phi']
    for x1 in [F(1), F(7, 8), F(3, 4), F(5, 8), F(1, 2), F(3, 8), F(1, 4),
               F(15, 16), F(13, 16), F(11, 16), F(9, 16)]:
        if time.time() - t0 > budget_s:
            return {'status': 'budget_exhausted', 'tried_up_to': str(x1)}
        Ms = {}
        for fp in fps:
            k11 = kernF[fp].subs({s_: sp.Rational(x1), u_: 1})
            k12 = kernF[fp].subs({s_: sp.Rational(x1)})          # u_ stays
            k22 = sp.expand(kernF[fp].subs({s_: sp.Rational(x1) * u_,
                                            u_: 1}))
            Ms[fp] = sp.expand(k11 + 2 * r_ * k12 + r_ ** 2 * k22)
        S = sp.expand(sum((1 if a == b else 2) * Ms[(a, b)]
                          for a, b in fps))
        eqs = []
        for fp in fps[:2]:      # two independent equations (third = norm)
            lam = sp.Rational(phiL[fp].numerator, phiL[fp].denominator)
            eqs.append(sp.expand(lam * S - Ms[fp]))
        R = sp.resultant(sp.Poly(eqs[0], r_), sp.Poly(eqs[1], r_), r_)
        Rp = sp.Poly(sp.expand(R), u_)
        if Rp.is_zero:
            continue
        try:
            roots = sp.polys.polytools.real_roots(Rp)
        except Exception:
            continue
        for u0 in roots:
            if not (0 < u0 < 1):
                continue
            # exact back-substitution: solve eqs[0] for r at u = u0
            p_r = sp.Poly(eqs[0].subs(u_, u0), r_)
            try:
                rroots = sp.polys.polytools.real_roots(p_r)
            except Exception:
                continue
            for r0 in rroots:
                if not (r0 > 0):
                    continue
                # exact verification of BOTH equations and all coords
                ok = True
                for fp in fps[:2]:
                    lam = sp.Rational(phiL[fp].numerator,
                                      phiL[fp].denominator)
                    val = sp.simplify((lam * S - Ms[fp])
                                      .subs({u_: u0, r_: r0}))
                    if val != 0:
                        ok = False
                        break
                if not ok:
                    continue
                # third coordinate implied by normalization; verify anyway
                fp3 = fps[2]
                lam = sp.Rational(phiL[fp3].numerator, phiL[fp3].denominator)
                val = sp.simplify((lam * S - Ms[fp3]).subs({u_: u0, r_: r0}))
                if val != 0:
                    continue
                return {'status': 'REALIZED',
                        'x1': str(x1),
                        'u_minpoly': str(sp.minimal_polynomial(u0, u_)),
                        'u_float': float(u0),
                        'x2_float': float(x1) * float(u0),
                        'r_minpoly': str(sp.minimal_polynomial(r0, r_)),
                        'r_float': float(r0),
                        'meaning': 'exact 2-atom Kingman product history '
                                   'whose folded normalized 2-SFS equals the '
                                   'folded Lambda point IDENTICALLY '
                                   '(sympy-verified): folded point IS in the '
                                   'folded class image'}
    return {'status': 'no_2atom_realization_found_on_scan'}

# ------------------------------------------------------------ one target: the decision chain

def decide(n, obj, fcomps, tgrid, kernF, kern, s_, u_):
    """Run inside_hunt -> witness_hunt -> outer_membership on one target and
    return the record {'n', 'phi_folded', 'inside_lp', 'verdict', ...certificate}.
    verdict: 'ANNIHILATED' (exact convex combination, 'inside_support_weights'),
    'SURVIVES_OUT_FULLCLASS' (certified full-class witness fields),
    'NO_LINEAR_WITNESS' (exact conic 'outer_membership'), else 'UNDECIDED'."""
    rec = {'n': n, 'phi_folded': {f'{a},{b}': str(obj['phi'][(a, b)])
                                  for a, b in FPAIRS(n)}}
    sol, status = inside_hunt(n, obj['phi'], fcomps, tgrid)
    rec['inside_lp'] = status
    if sol is not None:
        rec['verdict'] = 'ANNIHILATED'
        rec['inside_support_weights'] = sol
        return rec
    win, lp0 = witness_hunt(n, obj, kernF, kern, s_, u_)
    rec['witness_lp_delta0'] = lp0
    if win is not None:
        rec['verdict'] = 'SURVIVES_OUT_FULLCLASS'
        rec.update(win)
        return rec
    rec.update(outer_membership(n, obj, kernF, s_, u_))
    rec['verdict'] = 'NO_LINEAR_WITNESS' \
        if isinstance(rec.get('outer_membership'), dict) else 'UNDECIDED'
    return rec

# ------------------------------------------------------------ targets and ingredients

def _pair_key(k):
    """(i, j) from either a tuple or an 'i,j' string (JSON form)."""
    if isinstance(k, str):
        i, j = k.split(',')
        return (int(i), int(j))
    return (int(k[0]), int(k[1]))

def make_object(n, M):
    """Package a target for the deciders from its unnormalized second moments
    M = {(i,j) or 'i,j': E[L_i L_j]} (i <= j; Fractions, ints or 'p/q' strings):
    {'n', 'M', 'tot', 'q', 'phi'} with tot = full_sum(M), q = M / tot exact and
    phi = apply_fold(n, q), the folded normalized spectrum."""
    M = {_pair_key(k): F(v) for k, v in M.items()}
    assert set(M) == set(PAIRS(n)), "M must cover every stored coordinate i <= j"
    tot = full_sum(n, M)
    assert tot > 0, "second moments must have positive mass"
    q = {ij: M[ij] / tot for ij in PAIRS(n)}
    return {'n': n, 'M': M, 'tot': tot, 'q': q, 'phi': apply_fold(n, q)}

def fold_exprs(n, polys):
    """Phi applied entrywise to a dict of sympy expressions {(i,j): expr}
    (the two-time kernel or the diagonal polynomials) -> {(a,b): expanded
    expr}: the kernF / m2pF arguments of the hunts."""
    import sympy as sp
    return {fp: sp.expand(sum(sp.Integer(c) * polys[ij] for ij, c in co.items()))
            for fp, co in fold_coeffs(n).items()}

def load_reference_rows(path=None):
    """The shipped reference table (dict with 'ranks', 'rows',
    'realization_n4_beta_1_2'; exact entries as num/den strings)."""
    with open(path or ROWS_REF) as fh:
        return json.load(fh)

def load_ingredients(n, path=None):
    """Kingman-class polynomials at sample size n from the shipped file:
    {'n', 'm2_diag': {(i,j): {exponent: Fraction}},
     'twotime_kernel': {(i,j): {(es, eu): Fraction}}}."""
    with open(path or INGREDIENTS_REF) as fh:
        doc = json.load(fh)
    key = f'n{n}'
    if key not in doc:
        raise KeyError(f"no ingredients for n={n} in {path or INGREDIENTS_REF} "
                       f"(available: {[k for k in doc if k.startswith('n') and k[1:].isdigit()]})")
    blk = doc[key]
    m2 = {_pair_key(k): {int(e): F(c) for e, c in d.items()}
          for k, d in blk['m2_diag'].items()}
    kern = {_pair_key(k): {_pair_key(e): F(c) for e, c in d.items()}
            for k, d in blk['twotime_kernel'].items()}
    assert set(m2) == set(kern) == set(PAIRS(n)), "ingredient coordinates incomplete"
    return {'n': n, 'm2_diag': m2, 'twotime_kernel': kern}

def component_q(n, ing, t):
    """Normalized second moments {(i,j): Fraction} of the single-atom history at
    rational level t in [0,1], from the diagonal polynomials m2_ij(t). t = 0 is
    the directional limit t -> 0+: every m2_ij vanishes at t = 0 and the slowest
    term is t^1 (the last two lineages), so the limit of the normalized component
    is the normalized vector of t^1 coefficients."""
    t = F(t)
    m2 = ing['m2_diag']
    if t == 0:
        raw = {ij: p.get(1, F(0)) for ij, p in m2.items()}
    else:
        raw = {ij: sum(c * t ** e for e, c in p.items()) for ij, p in m2.items()}
    tot = full_sum(n, raw)
    assert tot > 0, f"component mass vanishes at t={t}"
    return {ij: raw[ij] / tot for ij in PAIRS(n)}

def folded_components(n, ing, tgrid):
    """[apply_fold(n, component_q(n, ing, t)) for t in tgrid]: the fcomps argument
    of inside_hunt, index-aligned with tgrid."""
    return [apply_fold(n, component_q(n, ing, t)) for t in tgrid]

def m2_sympy(ing, s_):
    """Diagonal polynomials as sympy expressions in s_: {(i,j): expr}."""
    import sympy as sp
    return {ij: sp.expand(sum(sp.Rational(c.numerator, c.denominator) * s_ ** e
                              for e, c in p.items()))
            for ij, p in ing['m2_diag'].items()}

def kernel_sympy(ing):
    """Two-time kernel as sympy expressions: ({(i,j): expr in (s, u)}, (s, u)),
    with s, u = sympy.symbols('s u', nonnegative=True)."""
    import sympy as sp
    s_, u_ = sp.symbols('s u', nonnegative=True)
    kern = {ij: sp.expand(sum(sp.Rational(c.numerator, c.denominator)
                              * s_ ** es * u_ ** eu for (es, eu), c in p.items()))
            for ij, p in ing['twotime_kernel'].items()}
    return kern, (s_, u_)

# ------------------------------------------------------------ main

def main(argv=None):
    ap = argparse.ArgumentParser(
        description="re-derive the folded two-site reference decisions from the "
                    "shipped Kingman-class ingredients")
    ap.add_argument('--n', type=int, choices=(4, 5, 6), default=None,
                    help="sample size to run (default: all of 4, 5, 6)")
    ap.add_argument('--out', default=None,
                    help="write the decision records as JSON to this file "
                         "(default: print only)")
    a = ap.parse_args(argv)
    import sympy as sp
    ref = load_reference_rows()
    want = (a.n,) if a.n else (4, 5, 6)
    tgrid = tgrid_of()
    out, bad = {'records': []}, []
    t0 = time.time()
    for n in want:
        ing = load_ingredients(n)
        fcomps = folded_components(n, ing, tgrid)
        kern, (s_, u_) = kernel_sympy(ing)
        kernF = fold_exprs(n, kern)
        s1 = sp.Symbol('s', nonnegative=True)
        m2pF = fold_exprs(n, m2_sympy(ing, s1))
        for row in (r for r in ref['rows'] if r['n'] == n):
            tag = f"n{n} {row['family']}" + (f" {row['param']}" if row['param'] else '')
            obj = make_object(n, row['M'])
            rec = decide(n, obj, fcomps, tgrid, kernF, kern, s_, u_)
            rec['family'], rec['param'] = row['family'], row['param']
            line = f"{tag:18s} {rec['verdict']:22s} (reference {row['verdict']})"
            if rec['verdict'] != row['verdict']:
                bad.append(tag)
                line += '  MISMATCH'
            if row['family'] == 'kingman' and rec['verdict'] == 'SURVIVES_OUT_FULLCLASS':
                bad.append(tag + ' sanity')
                line += '  SANITY-LAW VIOLATION'
            if rec['verdict'] == 'NO_LINEAR_WITNESS':
                w = diagonal_witness_hunt(n, obj, m2pF, s1, tgrid)
                rec['diagonal_witness'] = w
                line += (f"  diagonal witness margin {float(F(w['norm_margin_exact'])):.3e}"
                         if w else '  no diagonal witness')
            elif rec['verdict'] == 'ANNIHILATED':
                line += f"  {len(rec['inside_support_weights'])}-node support"
            print(line, flush=True)
            out['records'].append(rec)
    print(f"{len(out['records'])} targets, {len(bad)} mismatches "
          f"({time.time() - t0:.1f}s)")
    if a.out:
        with open(a.out, 'w') as fh:
            json.dump(out, fh, indent=1, default=str)
        print('wrote', a.out)
    return 1 if bad else 0

if __name__ == '__main__':
    sys.exit(main())
