#!/usr/bin/env python3
"""Acceptance tests for tools/formglue/form_route.py — STRICT, rc-coded, pytest-compatible.

Inputs are real FORM 5.0.1 diagrams_ output generated by
tests/fixtures/gen/gen_all.frm (the FORM 5 reference manual's gg->qqbar demo
model; see the credit comment in that file); the on-shell node-form dump is
verified BYTE-IDENTICAL to the reference dump fixtures/enum_1loop.out, the
30-diagram listing FORM 5.0.1 prints for that demo (read-only provenance check).

  (i)   demo 1-loop box: routed propagator-denominator set is equivalent to
        the HAND-WIRING of the demo's box numerator {k, k+p3, k+p3-p1,
        k-p4} up to loop-momentum redefinition k -> +-k + const — matched as
        SETS of momenta (exact Fraction vectors modulo overall external
        conservation and overall sign per propagator), not string equality;
  (ii)  the full 30-diagram on-shell enumeration routes with every
        self-check passing, count == 30 (node form, WithEdges_ form and the
        TopologiesOnly_+WithEdges_ census form; node vs edges forms agree);
  (iii) L>1: the shipped-example QCD 3-loop vacuum set (battery C count 74)
        routes 74/74 with L=3 everywhere, self-loops included;
  (iv)  mutation controls on SCRATCH COPIES: corrupt one edge -> router
        FAILS loudly (RouteError / CLI rc!=0). Includes the --mutate-edge
        assignment-corruption control that proves the vertex-conservation
        gate itself is live (a gate that cannot fail is void).

Run: python3 tools/formglue/tests/test_form_route.py   -> per-test PASS/FAIL, rc!=0 on any
     pytest tools/formglue/tests/test_form_route.py    -> same tests
"""

import os
import re
import subprocess
import sys
from fractions import Fraction

_HERE = os.path.dirname(os.path.abspath(__file__))
_PKG = os.path.dirname(_HERE)            # the formglue package dir
_TOOLS = os.path.dirname(_PKG)           # the repo tools/ dir
for _p in (_TOOLS, _PKG):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from form_route import RouteError, mom_str, route_file  # noqa: E402

GEN = os.path.join(_HERE, "fixtures", "gen")
BANKED = os.path.join(_HERE, "fixtures", "enum_1loop.out")
NODES = os.path.join(GEN, "enum_onshell_nodes.out")
EDGES = os.path.join(GEN, "enum_onshell_edges.out")
CENSUS = os.path.join(GEN, "census_topo.out")
VAC_E = os.path.join(GEN, "vac3_edges.out")
VAC_N = os.path.join(GEN, "vac3_nodes.out")
EXT = ["p1", "p2", "q1", "q2"]


# ------------------------------------------------- exact momentum-set algebra

def _reduce(vec, externals):
    """Eliminate the last external via overall conservation sum(ext) = 0."""
    out = {s: Fraction(c) for s, c in vec.items() if c}
    c = out.pop(externals[-1], Fraction(0))
    if c:
        for s in externals[:-1]:
            out[s] = out.get(s, Fraction(0)) - c
            if not out[s]:
                del out[s]
    return out


def _norm_const(vec, loop, externals):
    """Split a +-loop + const momentum: normalize to +loop, return the
    constant part as a hashable reduced vector."""
    v = _reduce(vec, externals)
    cl = v.pop(loop, Fraction(0))
    assert abs(cl) == 1, f"propagator momentum not +-{loop}+const: {vec}"
    if cl < 0:
        v = {s: -c for s, c in v.items()}
    return frozenset(v.items())


def _shift(const, delta):
    v = dict(const)
    for s, c in delta:
        v[s] = v.get(s, Fraction(0)) + c
        if not v[s]:
            del v[s]
    return frozenset(v.items())


def _equiv_up_to_loop_redef(consts_a, consts_b):
    """Sets of propagator constants equal under k -> +-k + c for some c?"""
    if len(consts_a) != len(consts_b):
        return False
    for sigma in (1, -1):
        bb = [frozenset((s, sigma * c) for s, c in b) for b in consts_b]
        a0 = next(iter(consts_a))
        for b0 in bb:
            delta = _shift(a0, [(s, -c) for s, c in b0])
            if {_shift(b, delta) for b in bb} == set(consts_a):
                return True
    return False


# ------------------------------------------------------------------ the tests

def test_provenance_regen_byte_identical():
    """Scratch regeneration == the reference dump fixtures/enum_1loop.out (read-only)."""
    with open(NODES, "rb") as f1, open(BANKED, "rb") as f2:
        assert f1.read() == f2.read(), \
            "regenerated enum_onshell_nodes.out != fixtures/enum_1loop.out"


def test_i_box_equivalent_to_hand_wiring():
    """Router's box == box_numerator.frm hand-wiring up to k -> +-k + const.

    Hand-wiring (box_numerator.frm, demo conventions p3,p4 OUTGOING):
    D1=(k+p3)^2, D2=(k+p3-p1)^2, D3=(k-p4)^2, D4=k^2. The enum runs
    all-incoming externals p1,p2,q1,q2 with q1=-p3, q2=-p4, so the reference
    denominator momenta are {k, k-q1, k-q1-p1, k+q2}.
    """
    dias = route_file(EDGES, externals=EXT)
    # structural selection of the quark-box candidates: 4 internal 3-point
    # vertices, internal edges = 3 quarks + 1 gluon (no ghosts), and the
    # internal gluon connects the two vertices carrying q1 and q2.
    candidates = []
    for d in dias:
        internal = [e for e in d.edges.values() if e.kind != "ext"]
        if len(internal) != 4 or d.V_int != 4:
            continue
        qs = [e for e in internal if e.field in ("qua", "QUA")]
        gs = [e for e in internal if e.field == "glu"]
        if len(qs) != 3 or len(gs) != 1:
            continue
        vq1 = next(v for e in d.edges.values() if e.kind == "ext" and "q1" in e.mom
                   for v in (e.v1, e.v2) if v not in d.leg_nodes)
        vq2 = next(v for e in d.edges.values() if e.kind == "ext" and "q2" in e.mom
                   for v in (e.v1, e.v2) if v not in d.leg_nodes)
        if {gs[0].v1, gs[0].v2} == {vq1, vq2}:
            candidates.append(d)
    assert len(candidates) == 2, \
        f"expected 2 quark-box candidates (uncrossed+crossed), got {len(candidates)}"

    # reference denominator constants in enum variables, loop symbol 'k'
    ref = [{"k": 1}, {"k": 1, "q1": -1}, {"k": 1, "q1": -1, "p1": -1},
           {"k": 1, "q2": 1}]
    ref_consts = {_norm_const(v, "k", EXT) for v in ref}
    assert len(ref_consts) == 4

    matches = []
    for d in candidates:
        loop = d.loop_syms[0]
        consts = {_norm_const(e.mom, loop, EXT)
                  for e in d.edges.values() if e.kind != "ext"}
        assert len(consts) == 4, f"diagram {d.idx}: degenerate denominators"
        if _equiv_up_to_loop_redef(consts, ref_consts):
            matches.append(d.idx)
    assert len(matches) == 1, \
        f"expected exactly ONE candidate equivalent to the hand-wired box " \
        f"(the other is the crossed box), got {matches}"


def test_ii_full_30_diagram_set_routes():
    for path, kw in ((NODES, dict(externals=EXT)), (EDGES, {}), ):
        dias = route_file(path, **kw)
        assert len(dias) == 30, f"{path}: {len(dias)} != 30 diagrams"
        for d in dias:
            assert d.L == 1 and d.E_int == d.V_int + d.L - 1
            names = [n for n, _ in d.checks]
            for want in ("externals-once", "vertex-conservation",
                         "euler-count", "betti-count", "chord-unit"):
                assert want in names, f"diagram {d.idx}: check {want} not run"
    # node form and WithEdges_ form must give the SAME routing
    da = route_file(NODES, externals=EXT)
    db = route_file(EDGES, externals=EXT)
    for x, y in zip(da, db):
        assert x.routing() == y.routing(), f"node/edges routing differs @ {x.idx}"
    # census (TopologiesOnly_+WithEdges_): 20 topologies, all route
    dc = route_file(CENSUS, externals=EXT)
    assert len(dc) == 20, f"census: {len(dc)} != 20 topologies"
    assert all(d.L == 1 for d in dc)


def test_iii_three_loop_vacuum_74():
    dias = route_file(VAC_E)
    assert len(dias) == 74, f"vacuum set: {len(dias)} != 74 diagrams"
    selfloops = 0
    for d in dias:
        assert d.L == 3, f"diagram {d.idx}: L={d.L} != 3"
        assert d.externals == []
        assert d.E_int == d.V_int + 2  # Euler with L=3
        selfloops += sum(1 for e in d.edges.values() if e.v1 == e.v2)
    assert selfloops > 0, "vacuum set contains no self-loops: weak test input"
    # node-form parity at 3 loops too
    dn = route_file(VAC_N)
    assert len(dn) == 74
    assert [d.routing() for d in dn] == [d.routing() for d in dias]


_MUT_SCRATCH = None


def _write_mut(name, text):
    # scratch copies go to a per-run tempdir, never into the package tree
    # (read-only checkouts; the vendored fixtures stay untouched)
    global _MUT_SCRATCH
    if _MUT_SCRATCH is None:
        import tempfile
        _MUT_SCRATCH = tempfile.mkdtemp(prefix="formglue_route_mut_")
    p = os.path.join(_MUT_SCRATCH, name)
    with open(p, "w") as f:
        f.write(text)
    return p


def test_iv_mutation_controls():
    """Corrupt ONE edge in scratch copies -> router must FAIL loudly.
    (Copies are unwrapped first: the corruption targets are otherwise split
    across FORM's wrapped lines; unwrapped text is valid router input.)"""
    from form_io import read_form_output
    raw = read_form_output(NODES)

    # (a) sign flip on one internal-edge occurrence: label appears twice with
    #     the same sign -> orientation is inconsistent -> loud RouteError
    anchor = "QUA(q1),qua(q2),glu(k4))+topo_(2)"  # end of diagram 1 (fixture layout)
    assert raw.count(anchor) == 1
    mut = _write_mut("mut_signflip.out",
                     raw.replace(anchor, "QUA(q1),qua(q2),glu(-k4))+topo_(2)", 1))
    try:
        route_file(mut, externals=EXT)
        raise AssertionError("sign-flip mutation ACCEPTED: router gate void")
    except RouteError:
        pass

    # (b) external duplicated (one leg label overwritten by another):
    #     'every external appears exactly once' must fire
    assert raw.count("node_(2,1,glu(-p2))") >= 1
    mut = _write_mut("mut_extdup.out",
                     raw.replace("node_(2,1,glu(-p2))", "node_(2,1,glu(-p1))", 1))
    try:
        route_file(mut, externals=EXT)
        raise AssertionError("duplicate-external mutation ACCEPTED")
    except RouteError:
        pass

    # (c) edge_ endpoint moved in the WithEdges_ form: node/edge cross-check
    rawe = read_form_output(EDGES)
    assert rawe.count("edge_(8,glu(k4),7,8)") >= 1
    mut = _write_mut("mut_endpoint.out",
                     rawe.replace("edge_(8,glu(k4),7,8)",
                                  "edge_(8,glu(k4),6,8)", 1))
    try:
        route_file(mut, externals=EXT)
        raise AssertionError("moved-endpoint mutation ACCEPTED")
    except RouteError:
        pass

    # (d) assignment corruption via the documented control hook: proves the
    #     VERTEX-CONSERVATION check itself is live (fires, not just parse guards)
    try:
        route_file(NODES, externals=EXT, mutate_edge="k1")
        raise AssertionError("--mutate-edge control ACCEPTED: conservation "
                             "gate is void")
    except RouteError as e:
        assert "CONSERVATION" in str(e), f"wrong gate fired: {e}"

    # (e) CLI rc-coding on a corrupted file (print-FAIL-exit-0 is banned)
    r = subprocess.run([sys.executable,
                        os.path.join(_PKG, "form_route.py"),
                        os.path.join(_MUT_SCRATCH, "mut_signflip.out"),
                        "--externals", ",".join(EXT)],
                       capture_output=True, text=True)
    assert r.returncode != 0, f"CLI rc=0 on corrupted input\n{r.stdout}{r.stderr}"
    assert "FAIL" in r.stderr

    # (f) positive control: the pristine file must still pass via CLI, rc=0
    r = subprocess.run([sys.executable,
                        os.path.join(_PKG, "form_route.py"),
                        NODES, "--externals", ",".join(EXT)],
                       capture_output=True, text=True)
    assert r.returncode == 0 and "ROUTED 30 diagrams" in r.stdout, \
        f"positive control failed: rc={r.returncode}\n{r.stdout}{r.stderr}"


def test_equiv_checker_mutation_control():
    """The set-equivalence comparator used in (i) must be able to FAIL:
    perturb one reference denominator constant -> no match."""
    ref = [{"k": 1}, {"k": 1, "q1": -1}, {"k": 1, "q1": -1, "p1": -1},
           {"k": 1, "q2": 1}]
    good = {_norm_const(v, "k", EXT) for v in ref}
    bad = [{"k": 1}, {"k": 1, "q1": -1}, {"k": 1, "q1": -1, "p1": -2},
           {"k": 1, "q2": 1}]
    badc = {_norm_const(v, "k", EXT) for v in bad}
    shifted = {_shift(c, [("p2", Fraction(3))]) for c in good}
    flipped = {frozenset((s, -c) for s, c in cc) for cc in good}
    assert _equiv_up_to_loop_redef(shifted, good), "shift invariance broken"
    assert _equiv_up_to_loop_redef(flipped, good), "sign invariance broken"
    assert not _equiv_up_to_loop_redef(badc, good), \
        "EQUIVALENCE COMPARATOR VOID: accepted a perturbed reference"


TESTS = [test_provenance_regen_byte_identical,
         test_i_box_equivalent_to_hand_wiring,
         test_ii_full_30_diagram_set_routes,
         test_iii_three_loop_vacuum_74,
         test_iv_mutation_controls,
         test_equiv_checker_mutation_control]


def main() -> int:
    fails = 0
    for t in TESTS:
        try:
            t()
            print(f"[PASS] {t.__name__}")
        except Exception as e:  # noqa: BLE001
            fails += 1
            print(f"[FAIL] {t.__name__}: {e}")
    print(f"TOTAL: {len(TESTS)} tests, {fails} failures")
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
