#!/usr/bin/env python3
"""Regression test for formglue.form_io.read_form_output — the #write mid-token
line-wrap fix. STRICT, rc-coded, pytest-compatible.

Fixtures are GENUINE FORM 5.0.1 output (generated by
tests/fixtures/routing_glue/gen_wrap_fixture.frm):
  wrap_fixture.out  — #write "%E" of (a+b+c+d)^6 with 78-char symbol names,
                      294 raw lines exhibiting BOTH wrap styles: backslash
                      MID-WORD splits (224 of them) and bare indented
                      token-boundary splits (gen_wrap_fixture.frm)
  cap_float.stdout  — stdout of a 120-digit mzv_(2,1) print (backslash wraps)

Checks:
  1. the fixture ACTUALLY wraps mid-token (backslash mid-word split exists,
     and a bare indented continuation exists);
  2. unwrapped expression == independent python multinomial expansion, all
     84 terms, exact integer coefficients;
  3. NAIVE reading (no unwrap) FAILS the same comparison (helper load-bearing);
  4. MUTATION control: corrupted scratch copy (continuation line dropped)
     FAILS the comparison;
  5. backslash-continuation stdout: extracted float == mpmath zeta(3) to
     >= 115 digits; record structure (blank-line reset) preserved.

Run: python3 tools/formglue/tests/test_form_io.py  -> per-test PASS/FAIL, rc!=0 on any
     pytest tools/formglue/tests/test_form_io.py   -> same tests
"""

import os
import re
import sys
from fractions import Fraction
from itertools import combinations_with_replacement

_HERE = os.path.dirname(os.path.abspath(__file__))
_PKG = os.path.dirname(_HERE)            # the formglue package dir
_TOOLS = os.path.dirname(_PKG)           # the repo tools/ dir
for _p in (_TOOLS, _PKG):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from form_io import read_form_output  # noqa: E402

FIX_DIR = os.path.join(_HERE, "fixtures", "routing_glue")
WRAP_FIX = os.path.join(FIX_DIR, "wrap_fixture.out")
FLOAT_FIX = os.path.join(FIX_DIR, "cap_float.stdout")
SYMS = tuple(c * 76 + f"x{i+1}" for i, c in enumerate("abcd"))
POWER = 6


def _expected_expansion():
    """Independent exact multinomial expansion of (s1+s2+s3+s4)^POWER."""
    import math
    out = {}
    for combo in combinations_with_replacement(range(len(SYMS)), POWER):
        exps = [0] * len(SYMS)
        for i in combo:
            exps[i] += 1
        coeff = math.factorial(POWER)
        for e in exps:
            coeff //= math.factorial(e)
        out[tuple(exps)] = coeff
    return out


def _parse_expansion(text):
    """Parse 'FIX=term+term+...;' into {exponent-tuple: coeff}. STRICT."""
    s = text.strip()
    if not s.startswith("FIX=") or not s.endswith(";"):
        raise ValueError(f"bad expression envelope: {s[:40]!r}...{s[-20:]!r}")
    s = s[len("FIX="):-1]
    if any(ch.isspace() for ch in s):
        raise ValueError("whitespace inside expression (unjoined wrap?)")
    terms = s.split("+")
    out = {}
    for t in terms:
        coeff, exps = 1, [0] * len(SYMS)
        for fac in t.split("*"):
            m = re.match(r"^(\d+)$", fac)
            if m:
                coeff *= int(m.group(1))
                continue
            m = re.match(r"^([A-Za-z][A-Za-z0-9]*)(?:\^(\d+))?$", fac)
            if not m or m.group(1) not in SYMS:
                raise ValueError(f"unparseable factor {fac!r} in term {t!r}")
            exps[SYMS.index(m.group(1))] += int(m.group(2) or 1)
        key = tuple(exps)
        if key in out:
            raise ValueError(f"duplicate monomial {key}")
        out[key] = coeff
    return out


def test_fixture_genuinely_wraps():
    with open(WRAP_FIX) as f:
        raw = f.read()
    lines = raw.splitlines()
    assert len(lines) >= 2, "fixture is a single line: does not wrap"
    conts = [ln for ln in lines[1:] if ln[:1] in (" ", "\t")]
    assert conts, "no indented continuation lines in fixture"
    # genuine mid-word wraps: FORM marks them with a trailing backslash
    midword = [ln for ln in lines if ln.endswith("\\")]
    assert midword, "no MID-WORD (backslash) wrap in fixture (regenerate)"
    # and bare indented continuations at token boundaries must also occur
    bare = [b for a, b in zip(lines, lines[1:])
            if not a.endswith("\\") and b[:1] in (" ", "\t")]
    assert bare, "no bare indented wrap in fixture (regenerate)"


def test_unwrap_matches_independent_expansion():
    got = _parse_expansion(read_form_output(WRAP_FIX))
    want = _expected_expansion()
    assert len(got) == 84, f"expected 84 terms, got {len(got)}"
    assert got == want, "unwrapped expansion != independent multinomial expansion"


def test_naive_read_fails():
    """Load-bearing control: parsing the RAW wrapped file must FAIL."""
    with open(WRAP_FIX) as f:
        raw = f.read()
    try:
        got = _parse_expansion(raw)
    except ValueError:
        return  # failed loudly, as required
    assert got != _expected_expansion(), \
        "naive (no-unwrap) read PASSED the comparison: control is void"


def test_mutation_control_corrupted_copy_fails():
    """Drop one continuation line in a SCRATCH COPY -> comparison must fail."""
    # scratch goes to a per-run tempdir, never into the package tree
    # (read-only checkouts; the vendored fixtures stay untouched)
    import tempfile
    mut_dir = tempfile.mkdtemp(prefix="formglue_io_mut_")
    with open(WRAP_FIX) as f:
        lines = f.read().splitlines(keepends=True)
    assert len(lines) > 10
    mut = os.path.join(mut_dir, "wrap_fixture_dropline.out")
    with open(mut, "w") as f:
        f.writelines(lines[:7] + lines[8:])  # drop the 8th raw line
    try:
        got = _parse_expansion(read_form_output(mut))
    except ValueError:
        return  # loud failure is a pass for the control
    assert got != _expected_expansion(), \
        "MUTATION CONTROL VOID: corrupted fixture still matched"


def test_backslash_stdout_style():
    """Real FORM float stdout: backslash wrap joined, record structure kept,
    value correct vs mpmath to >= 115 digits."""
    txt = read_form_output(FLOAT_FIX)
    hits = re.findall(r"^\s+FORACLE\s*=\s*([^;]+);", txt, flags=re.M)
    assert len(hits) == 1, f"expected 1 FORACLE record, got {len(hits)}"
    val = hits[0].strip()
    assert re.match(r"^[-+]?\d+\.\d+e[+-]?\d+$", val), f"malformed float {val!r}"
    import mpmath as mp
    with mp.workdps(140):
        d = abs(mp.mpf(val) - mp.zeta(3))
        digs = float(-mp.log10(d / mp.zeta(3))) if d else float("inf")
    assert digs >= 115, f"only {digs:.1f} digits vs mpmath zeta(3)"


TESTS = [test_fixture_genuinely_wraps,
         test_unwrap_matches_independent_expansion,
         test_naive_read_fails,
         test_mutation_control_corrupted_copy_fails,
         test_backslash_stdout_style]


def main() -> int:
    fails = 0
    for t in TESTS:
        try:
            t()
            print(f"[PASS] {t.__name__}")
        except Exception as e:  # noqa: BLE001
            fails += 1
            print(f"[FAIL] {t.__name__}: {e}")
    print(f"TOTAL: {len(TESTS)} tests, {fails} failures")
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
