"""COMPAT SHIM — executes the canonical body in build/abcount/ under this
module name.

Forwards the abcount import form `import abcount_s3` to the canonical
byte-identical body at tools/abacus/build/abcount/abcount_s3.py (see
tools/abacus/README.md).
Do not edit this file or the body: the body's bytes are sha-pinned by the
verification harness — changes there make verification fail."""
import importlib.util as _ilu
import os as _os
import sys as _sys

_BODY = _os.path.join(_os.path.dirname(_os.path.abspath(__file__)),
                      "build", "abcount", "abcount_s3.py")
_BODYDIR = _os.path.dirname(_BODY)
if _BODYDIR not in _sys.path:
    _sys.path.insert(0, _BODYDIR)   # sibling imports resolve to canonical bodies
_spec = _ilu.spec_from_file_location("abcount_s3", _BODY)
_mod = _ilu.module_from_spec(_spec)
_sys.modules["abcount_s3"] = _mod           # import returns the canonical module
_spec.loader.exec_module(_mod)
globals().update({_k: _v for _k, _v in _mod.__dict__.items()
                  if not _k.startswith("__")})
