#!/usr/bin/env python3
"""assemble_etas_np — fast numpy replication of the pinned package's
calculate_distances pair table (hi floors; the package's own per-source
pandas loop needs ~4h at 130k sources). Conventions transliterated
EXACTLY from the pinned etas.inversion (sha receipted in the journal):
round_half_up magnitude binning; catalog filter m >= mc; targets =
events with time >= timewindow_start; pair rule STRICT t_target >
t_source; cutoff r^2 <= (coppersmith_SSRL(fault 4) * multiplier)^2 with
SSRL = 10^(0.59 m - 2.44) km on the ROUNDED magnitude; haversine
distance, R = 6.3781e3 km.

IDENTITY CHAIN (because this table is transliterated, not regenerated by
the package): (a) n_sources/n_targets must equal the banked fit's; (b)
the E-step state at the banked theta recomputed over THIS pair table
must reproduce the banked fit artifacts of record — P_background per
target and l_hat per source (final-theta register, strict bars) and
n_hat (exact); the banked G column is the penultimate-theta register
(receipted at its own bar); (c) when the package's own dump lands
(etas_dump.py, still running), diff_pair_tables.py must report EXACT
set equality — the final receipt.

Usage: assemble_etas_np.py <e2_params.json> <catalog.csv>
       <banked_sources.csv> <banked_trigbg.csv> <out.npz>
"""
import json
import sys

import numpy as np
import pandas as pd


# round_half_up is copied from etas/mc_b_est.py (github.com/lmizrahi/etas @ 097f08b6, MIT, Copyright (c) 2024 ETH Zurich, Leila Mizrahi); see PROVENANCE.md.
def round_half_up(n, decimals=0):
    multiplier = 10 ** decimals
    return np.floor(n * multiplier + 0.5) / multiplier


def main():
    e2_p, cat_p, src_p, trg_p, out_p = sys.argv[1:6]
    e2 = json.load(open(e2_p))
    cfg = e2["config"]
    mc = float(cfg["mc"])
    delta_m = float(cfg["delta_m"])
    mult = float(cfg["coppersmith_multiplier"])
    tw_start = pd.Timestamp(cfg["timewindow_start"])
    tw_end = pd.Timestamp(cfg["timewindow_end"])
    aux_start = pd.Timestamp(cfg["auxiliary_start"])
    sc = np.asarray(cfg["shape_coords"], float)
    lat_lo, lat_hi = sc[:, 0].min(), sc[:, 0].max()
    lon_lo, lon_hi = sc[:, 1].min(), sc[:, 1].max()
    cat = pd.read_csv(cat_p)
    cat["time"] = pd.to_datetime(cat["time"])
    mag = round_half_up(cat["magnitude"].to_numpy() / delta_m) * delta_m
    keep = mag >= mc            # mc_current = mc (constant branch)
    # filter_catalog: aux window [aux_start, tw_end) + region polygon
    # (rectangle here; shapely intersects keeps the boundary -> inclusive)
    keep &= ((cat["time"] >= aux_start) & (cat["time"] < tw_end)
             ).to_numpy()
    keep &= ((cat["latitude"].to_numpy() >= lat_lo)
             & (cat["latitude"].to_numpy() <= lat_hi)
             & (cat["longitude"].to_numpy() >= lon_lo)
             & (cat["longitude"].to_numpy() <= lon_hi))
    cat = cat[keep].reset_index(drop=False)
    mag = mag[keep]
    t_days = ((cat["time"] - tw_start) / pd.Timedelta(days=1)).to_numpy()
    lat = np.radians(cat["latitude"].to_numpy())
    lon = np.radians(cat["longitude"].to_numpy())
    is_target = t_days >= 0.0
    tgt_idx = np.where(is_target)[0]
    n_s = len(cat)
    n_t = len(tgt_idx)
    assert n_t == e2["n_target_events"], (n_t, e2["n_target_events"])
    # cutoff^2 per source (rounded magnitude; SSRL fault type 4)
    ssrl = np.power(10.0, 0.59 * mag - 2.44)
    cut2 = np.square(ssrl * mult)
    te = ((tw_end - cat["time"]) / pd.Timedelta(days=1)).to_numpy()
    ts = np.clip(((tw_start - cat["time"])
                  / pd.Timedelta(days=1)).to_numpy(), 0.0, None)
    R = 6.3781e3
    tlat = lat[tgt_idx]
    tlon = lon[tgt_idx]
    tt = t_days[tgt_idx]
    pos_of = np.full(n_s, -1, np.int64)
    pos_of[tgt_idx] = np.arange(n_t)
    ps, pt, pdt, pr2, pm = [], [], [], [], []
    CH = 400
    for s0 in range(0, n_s, CH):
        s1 = min(s0 + CH, n_s)
        sl = lat[s0:s1][:, None]
        so = lon[s0:s1][:, None]
        d = 2 * R * np.arcsin(np.sqrt(
            np.square(np.sin((sl - tlat[None, :]) / 2))
            + np.cos(sl) * np.cos(tlat[None, :])
            * np.square(np.sin((so - tlon[None, :]) / 2))))
        r2 = np.square(d)
        dt = tt[None, :] - t_days[s0:s1][:, None]
        m_ok = (r2 <= cut2[s0:s1][:, None]) & (dt > 0.0)
        si, ti = np.where(m_ok)
        ps.append((si + s0).astype(np.int32))
        pt.append(ti.astype(np.int32))
        pdt.append(dt[si, ti])
        pr2.append(r2[si, ti])
        pm.append(mag[si + s0])
    ps = np.concatenate(ps)
    pt = np.concatenate(pt)
    pdt = np.concatenate(pdt)
    pr2 = np.concatenate(pr2)
    pm = np.concatenate(pm)
    print("pairs:", len(ps), "sources:", n_s, "targets:", n_t)
    # ---- E-step identity vs the banked fit artifacts ----------------
    th = e2["final_parameters"]
    m_ref = float(e2["m_ref"])
    mc_min = m_ref - delta_m / 2
    mu = 10.0 ** th["log10_mu"]
    k0 = 10.0 ** th["log10_k0"]
    c = 10.0 ** th["log10_c"]
    tau = 10.0 ** th["log10_tau"]
    d_ = 10.0 ** th["log10_d"]
    a, om, gam, rho = (th["a"], th["omega"], th["gamma"], th["rho"])
    dm = pm - mc_min
    g = (k0 * np.exp(a * dm)
         * np.exp(-pdt / tau) / np.power(pdt + c, 1 + om)
         / np.power(pr2 + d_ * np.exp(gam * dm), 1 + rho))
    lam = mu + np.bincount(pt, weights=g, minlength=n_t)
    pbg = mu / lam
    lhat = np.bincount(ps, weights=g / lam[pt], minlength=n_s)
    bt = pd.read_csv(trg_p)
    bs = pd.read_csv(src_p)
    # align by original catalog id
    orig_id = cat["id"].to_numpy() if "id" in cat.columns else \
        cat["index"].to_numpy()
    tid_pos = {int(v): i for i, v in enumerate(orig_id[tgt_idx])}
    sid_pos = {int(v): i for i, v in enumerate(orig_id)}
    bt_pos = np.array([tid_pos[int(v)] for v in bt["target_id"]])
    bs_pos = np.array([sid_pos[int(v)] for v in bs["source_id"]])
    dev_pbg = float(np.abs(pbg[bt_pos] - bt["P_background"].to_numpy())
                    .max())
    dev_lhat = float(np.abs(lhat[bs_pos] - bs["l_hat"].to_numpy()).max())
    dev_nhat = float(abs(pbg.sum() - e2["n_hat"]))
    # G at banked theta (twin formula) vs banked CSV (penultimate reg.)
    from twin_etas import upper_gamma_ext
    kapS = k0 * np.exp(a * (mag - mc_min))
    DbS = d_ * np.exp(gam * (mag - mc_min))
    areaF = np.pi * np.power(DbS, -rho) / rho
    x1 = (ts + c) / tau
    x2 = (te + c) / tau
    tf = (np.exp(c / tau) * np.power(tau, -om)
          * (upper_gamma_ext(-om, x1) - upper_gamma_ext(-om, x2)))
    G = kapS * areaF * tf
    dev_G_banked = float(np.abs(G[bs_pos] - bs["G"].to_numpy()).max())
    tw_length = float((tw_end - tw_start) / pd.Timedelta(days=1))
    print(json.dumps(dict(dev_pbg=dev_pbg, dev_lhat=dev_lhat,
                          dev_nhat=dev_nhat,
                          dev_G_banked_penultimate=dev_G_banked)))
    assert dev_pbg < 1e-12 and dev_lhat < 1e-9 and dev_nhat < 1e-6
    src_G_pos = np.empty(n_s)
    src_G_pos[bs_pos] = bs["G"].to_numpy()
    src_lhat_pos = np.empty(n_s)
    src_lhat_pos[bs_pos] = bs["l_hat"].to_numpy()
    trg_pbg_pos = np.empty(n_t)
    trg_pbg_pos[bt_pos] = bt["P_background"].to_numpy()
    np.savez_compressed(
        out_p, pair_s=ps, pair_t=pt, pair_dt=pdt, pair_r2=pr2,
        pair_m=pm, src_m=mag, src_ts=ts, src_te=te,
        src_G=src_G_pos, src_lhat=src_lhat_pos, trg_pbg=trg_pbg_pos,
        trg_totrate=lam,
        theta=np.array([th["log10_mu"], np.nan, th["log10_k0"], a,
                        th["log10_c"], om, th["log10_tau"],
                        th["log10_d"], gam, rho], np.float64),
        beta=np.float64(e2["beta"]), area=np.float64(e2["area_km2"]),
        tw_length=np.float64(tw_length),
        m_ref=np.float64(m_ref), delta_m=np.float64(delta_m),
        mc_min=np.float64(mc_min), n_hat=np.float64(e2["n_hat"]),
        n_hat_banked=np.float64(e2["n_hat"]),
        g_register=np.bytes_(b"banked-penultimate"))
    print("->", out_p)


if __name__ == "__main__":
    main()
