"""EtasOracle — ball-rigorous oracle for the ETAS (Ogata 1988) incomplete-data
(observed) negative log-likelihood as implemented in the etas package of
Mizrahi, Nandan & Wiemer (2021), the objective the package's EM
ascends (constant-background branch, xi = zeta = 1, receipted):

  NLL(th) = - sum_t log lam_t + mu*A*T + sum_j G_j
  lam_t   = mu + sum_{p in P(t)} g_p
  g_p     = kappa(m) * e^{-dt/tau} (dt+c)^{-(1+om)} * (r2+D(m))^{-(1+rho)}
  kappa   = k0 e^{a(m-mc_min)},  D = d e^{gamma(m-mc_min)}
  G_j     = kappa(m_j) * [pi D^-rho / rho] * TF_j
  TF_j    = int_{ts_j}^{te_j} e^{-t/tau} (t+c)^{-(1+om)} dt
          = e^{c/tau} tau^{-om} [ gamma_low(s,x2) - gamma_low(s,x1) ],
            s = -om, x_i = (t_i+c)/tau   (Gamma(s) cancels in the diff)

theta (9): [log10_mu, log10_k0, a, log10_c, omega, log10_tau, log10_d,
gamma, rho]. Pair table P(t) = the package's calculate_distances output,
regenerated by the pinned env and consumed by identity (etas_dump.py).

Pairs side: hand-assembled first/second log-derivatives (sparse exact
forms), accumulated per target then
combined through log. Sources side: 3-var second-order jets (clinch.jets
by identity) with gamma_low via the Kummer series
  gamma_low(s,x) = x^s e^{-x} sum_{n>=0} x^n / (s(s+1)...(s+n)),
run past value convergence with EXPLICIT tail enclosures on every jet
component (value/grad/hess tails bounded via sum (n+1)^2 |t_n| bounds and
the distance of the s ball to its nearest pole) — rigorous, no shrug.

Parallel: fork workers over target/source chunks; partial sums cross the
process boundary as EXACT (man, exp) integer quadruples (midpoint exact,
radius outward) — no lossy serialization.
"""
import os
import numpy as np
from flint import arb, ctx

from clinch.jets import Jet, jvar
from clinch.oracle_v31 import OracleRefusal

__all__ = ["EtasOracle", "Part", "OracleRefusal"]

LN10 = None


class Part:
    def __init__(self, blocks, block_names, border_idx):
        self.blocks = [np.asarray(b, dtype=int) for b in blocks]
        self.block_names = list(block_names)
        self.border_idx = np.asarray(border_idx, dtype=int)


# ---------------------------------------------------------------------
# exact serialization (man_exp quadruples)
# ---------------------------------------------------------------------
def ser(a):
    m, e = a.mid().man_exp()
    rm, re = a.rad().man_exp()
    return (int(m), int(e), int(rm), int(re))


def deser(t):
    m, e, rm, re = t
    mid = arb(m) * arb(2) ** e
    rad = arb(rm) * arb(2) ** re
    return arb(mid, rad)


# ---------------------------------------------------------------------
# lower incomplete gamma (regular part) as a 3-var order-2 jet
# ---------------------------------------------------------------------
def gamma_low_jet(s, x, order2):
    """gamma_low(s,x) jet: s, x are Jets (3-var). Kummer series with
    certified tails on EVERY component. Requires x.v > 0 and the s ball
    to exclude {0, -1, -2, ...} (checked)."""
    if not (x.v > 0):
        raise OracleRefusal("gamma_low", "x not provably > 0")
    # distance of s ball to the nearest pole (0, -1, -2)
    slo = None
    for k in range(0, 3):
        dk = (s.v + k).abs_lower()
        if not (dk > 0):
            raise OracleRefusal("gamma_low", f"s ball touches pole -{k}")
        slo = dk if slo is None or dk < slo else slo
    xu = x.v.abs_upper()
    W_up = arb(10).log().abs_upper()
    # per-jet-var first-derivative log-factor bound for term t_n:
    #   d/ds: sum_k 1/|s+k| <= (n+1)/slo;  d/dx routes (x = (t+c)/tau):
    #   |dlog t_n / d(lc or ltau)| <= n*W — combined majorant
    #   (n+1)*g1, g1 = 1/slo + W (sum >= max); second order: 2(n+1)^2 g1^2
    g1 = 1 / slo + W_up
    # t_0 = 1/s;  t_n = t_{n-1} * x / (s+n)
    t = s._recip()
    S = t
    tail_ok = False
    n = 0
    NMAX = 400
    eps = arb(2) ** (-200)
    while n < NMAX:
        n += 1
        t = t * x / (s + n)
        S = S + t
        u = xu / (n + 1)
        if u < 0.5:
            tval = t.v.abs_upper()
            base = tval * u / (1 - u)
            # value tail <= base; grad tail <= 2*base*(n+2)*g1/(1-u);
            # hess tail <= 8*base*(n+2)^2*g1^2/(1-u)^2 (u<1/2 majorants,
            # explicit safety factors)
            t0 = base
            t1 = 2 * base * (n + 2) * g1 / (1 - u)
            t2 = 8 * base * (n + 2) * (n + 2) * g1 * g1 \
                / (1 - u) / (1 - u)
            worst = t2
            if t1 > worst:
                worst = t1
            if t0 > worst:
                worst = t0
            if worst < eps * S.v.abs_lower() + eps:
                pad = arb(0, worst)
                S = Jet(S.v + pad,
                        [gg + pad for gg in S.g],
                        None if S.h is None else
                        [hh + pad for hh in S.h], S.n)
                tail_ok = True
                break
    if not tail_ok:
        raise OracleRefusal("gamma_low",
                            f"Kummer series no certified tail by {NMAX}")
    xs = (s * x.log()).exp()
    return xs * (-x).exp() * S


def _phi_expm1_jet(z, order2):
    """phi(z) = expm1(z)/z as a jet, safe when the z ball contains 0:
    for |z| provably < 0.5 use the series sum_{k>=0} z^k/(k+1)! with a
    certified all-component tail; else the direct expm1(z)/z."""
    zu = z.v.abs_upper()
    if zu < 0.5:
        S = Jet.const(arb(1), z.n, order2)
        t = Jet.const(arb(1), z.n, order2)
        fac = arb(1)
        K = 40
        for k in range(1, K + 1):
            t = t * z
            fac = fac / (k + 1)
            S = S + t * fac
        # tail: sum_{k>K} |z|^k/(k+1)! <= zu^{K+1}/(K+2)! * 1/(1-zu);
        # jet-derivative factors <= (k+1) per order (d/dz z^k = k z^{k-1},
        # |z|<1) — majorant 8*(K+3)^2 covers both orders (zu<1/2)
        pw = arb(1)
        for _ in range(K + 1):
            pw *= zu
        f = arb(1)
        for k in range(2, K + 3):
            f *= k
        # jet-component bound from the ACTUAL z jet (rigorous):
        zb = arb(1)
        for gcomp in z.g:
            zb += gcomp.abs_upper()
        if z.h is not None:
            for hcomp in z.h:
                zb += hcomp.abs_upper()
        tail = pw / f / (1 - zu) * 8 * zb * zb * (K + 3) * (K + 3)
        pad = arb(0, tail.abs_upper())
        return Jet(S.v + pad, [g + pad for g in S.g],
                   None if S.h is None else [h + pad for h in S.h], S.n)
    return z.expm1() / z


def delta_gamma_low_jet(s, x1, x2, order2):
    """DELTA of lower incomplete gammas, POLE-FREE at s = 0:
      gamma(s,x2) - gamma(s,x1)
        = sum_{n>=0} (-1)^n/n! * (x2^{s+n} - x1^{s+n})/(s+n)
    with the n = 0 term computed as e^{s L1} * (L2-L1) * phi(s (L2-L1)),
    phi = expm1(z)/z (the removable-singularity form; L = log x). Cures
    the s->0 width blow-up of the per-gamma Kummer route (JOURNAL gate
    catch #5: at the hi-target corners omega ~ +2e-4, each gamma's jet
    carries 1/s^3-scale components whose widths explode while the
    DIFFERENCE is finite). Requires x1, x2 provably > 0 and the s ball
    to exclude {-1, -2, ...} (s = 0 is FINE here); designed for the
    x <= ~1e-2 regime (fast alternating convergence; checked)."""
    if not (x1.v > 0) or not (x2.v > 0):
        raise OracleRefusal("delta_gamma", "x not provably > 0")
    if not (s.v.abs_upper() < 0.5):
        raise OracleRefusal("delta_gamma",
                            "|s| < 0.5 not provable (pole margin)")
    x2u = x2.v.abs_upper()
    x1u = x1.v.abs_upper()
    xu = x2u if x2u > x1u else x1u
    if not (xu < 0.01):
        raise OracleRefusal("delta_gamma",
                            "x outside the small-x design regime")
    L1 = x1.log()
    L2 = x2.log()
    dL = L2 - L1
    z = s * dL
    D0 = (s * L1).exp() * dL * _phi_expm1_jet(z, order2)
    S = D0
    # n >= 1 terms
    Lmax = L1.v.abs_upper()
    if L2.v.abs_upper() > Lmax:
        Lmax = L2.v.abs_upper()
    sign = -1
    fac = arb(1)
    N = 8
    for n in range(1, N + 1):
        fac = fac * n
        Dn = ((s + n) * L2).exp() - ((s + n) * L1).exp()
        Dn = Dn / (s + n)
        S = S + Dn * (sign / fac)
        sign = -sign
    # tail: |term_n| <= 2*xu^{n+s_lo}/((n-1)*n!) class; with s in
    # (-0.5, 0.5) and xu < 0.01, |x^{s+n}| <= xu^{n-0.5}; majorant with
    # jet-derivative factors <= (Lmax+2)(n+2) per order, safety 8
    pw = arb(1)
    for _ in range(N):
        pw *= xu          # xu^N  (>= xu^{N+1-0.5} for xu<1)
    facN = arb(1)
    for k in range(1, N + 2):
        facN *= k
    base = 4 * pw / facN / (1 - xu)
    gf = (Lmax + 2) * (N + 3)
    worst = base * 8 * gf * gf
    pad = arb(0, worst.abs_upper())
    return Jet(S.v + pad, [g + pad for g in S.g],
               None if S.h is None else [h + pad for h in S.h], S.n)


# ---------------------------------------------------------------------
# worker kernels
# ---------------------------------------------------------------------
_G = {}      # worker globals set by fork


def _theta_balls(th_ser, prec):
    ctx.prec = prec
    return [deser(t) for t in th_ser]


def _pairs_chunk(args):
    """-sum_t log lam_t over targets [t0,t1) + its grad/hess pieces."""
    (t0, t1, th_ser, prec, order) = args
    d = _G
    th = _theta_balls(th_ser, prec)
    lmu, lk0, av, lc, om, lt, ld, gm, rho = th
    W = arb(10).log()
    mu = (lmu * W).exp()
    c = (lc * W).exp()
    tau = (lt * W).exp()
    itau = 1 / tau
    k0 = (lk0 * W).exp()
    dd = (ld * W).exp()
    one_om = 1 + om
    one_rho = 1 + rho
    muW = mu * W
    muW2 = muW * W
    # per-bin constants
    bins = d["bins"]                     # float dm values
    kap_b = []
    D_b = []
    dm_b = []
    for dmv in bins:
        dmb = arb(dmv)
        kap_b.append(k0 * (av * dmb).exp())
        D_b.append(dd * (gm * dmb).exp())
        dm_b.append(dmb)
    cW1om = c * W * one_om               # d3 = -cW1om * iP
    Witau = W * itau                     # d5 = Witau * dt
    W1rho = W * one_rho                  # d6 = -W1rho * q
    c33 = one_om * W * W * c             # h33 = -c33 * dt * iP^2
    cW = c * W                           # h34 = -cW * iP  (d/dom of d3... )
    W2 = W * W
    ps = d["ps"]; pt = d["pt"]
    pdt = d["pdt"]; pr2 = d["pr2"]; pbin = d["pbin"]
    tptr = d["tptr"]
    val = arb(0)
    grad = [arb(0) for _ in range(9)]
    hess = [[arb(0)] * 9 for _ in range(9)] if order >= 2 else None
    z = arb(0)
    for t in range(t0, t1):
        i0, i1 = tptr[t], tptr[t + 1]
        S0 = arb(0)
        S1 = [z] * 9
        S2 = [[z] * 9 for _ in range(9)] if order >= 2 else None
        for i in range(i0, i1):
            b = pbin[i]
            dt_ = arb(float(pdt[i]))
            r2 = arb(float(pr2[i]))
            P = dt_ + c
            iP = 1 / P
            L = P.log()
            Tv = (-dt_ * itau - one_om * L).exp()
            Db = D_b[b]
            R = r2 + Db
            iR = 1 / R
            M = R.log()
            q = Db * iR
            Sv = (-one_rho * M).exp()
            g = kap_b[b] * Tv * Sv
            dm = dm_b[b]
            d3 = -cW1om * iP
            d4 = -L
            d5 = Witau * dt_
            d6 = -W1rho * q
            d7 = -one_rho * dm * q
            d8 = -M
            dvec = (W, dm, d3, d4, d5, d6, d7, d8)   # indices 1..8
            S0 += g
            for k in range(8):
                S1[k + 1] = S1[k + 1] + g * dvec[k]
            if order >= 2:
                iP2 = iP * iP
                h33 = -c33 * dt_ * iP2
                h34 = -cW * iP
                h55 = -W * d5            # = -W^2 dt itau
                q1q = q * (1 - q)
                h66 = -one_rho * W2 * q1q
                h67 = -one_rho * W * dm * q1q
                h77 = -one_rho * dm * dm * q1q
                h68 = -W * q
                h78 = -dm * q
                hmap = {(3, 3): h33, (3, 4): h34, (5, 5): h55,
                        (6, 6): h66, (6, 7): h67, (7, 7): h77,
                        (6, 8): h68, (7, 8): h78}
                for k in range(8):
                    dk = dvec[k]
                    gk = g * dk
                    for l in range(k, 8):
                        e = dk * dvec[l]
                        hkl = hmap.get((k + 1, l + 1))
                        if hkl is not None:
                            e = e + hkl
                        S2[k + 1][l + 1] = S2[k + 1][l + 1] + g * e
        lam = mu + S0
        if not (lam > 0):
            raise OracleRefusal("lam_pos",
                                f"lam not provably > 0 at target {t}")
        il = 1 / lam
        val -= lam.log()
        gl = [muW] + [S1[k] for k in range(1, 9)]
        for k in range(9):
            grad[k] -= gl[k] * il
        if order >= 2:
            il2 = il * il
            Hl = [[z] * 9 for _ in range(9)]
            Hl[0][0] = muW2
            for k in range(1, 9):
                for l in range(k, 9):
                    Hl[k][l] = S2[k][l]
            for k in range(9):
                glk = gl[k]
                for l in range(k, 9):
                    hess[k][l] += glk * gl[l] * il2 - Hl[k][l] * il
    out = [ser(val)] + [ser(v) for v in grad]
    if order >= 2:
        for k in range(9):
            for l in range(k, 9):
                out.append(ser(hess[k][l]))
    return out


def _sources_chunk(args):
    """sum_j G_j over sources [j0,j1) + grad/hess pieces (9-dim)."""
    (j0, j1, th_ser, prec, order) = args
    d = _G
    th = _theta_balls(th_ser, prec)
    lmu, lk0, av, lc, om, lt, ld, gm, rho = th
    W = arb(10).log()
    order2 = order >= 2
    # jets in 3 vars (lc, om, ltau) for the TF factor
    lcj = jvar(lc, 0, 3, order2)
    omj = jvar(om, 1, 3, order2)
    ltj = jvar(lt, 2, 3, order2)
    cj = (lcj * W).exp()
    tj = (ltj * W).exp()
    itj = tj._recip()
    sj = -omj
    pref = (cj * itj).exp() * ((-omj) * (ltj * W)).exp()   # e^{c/tau} tau^-om
    src_m = d["src_m"]; src_ts = d["src_ts"]; src_te = d["src_te"]
    k0 = (lk0 * W).exp()
    dd = (ld * W).exp()
    irho = 1 / rho
    piA = arb.pi()
    lnD_base = ld * W        # lnD = ld*W + gm*dm
    val = arb(0)
    grad = [arb(0) for _ in range(9)]
    hess = [[arb(0)] * 9 for _ in range(9)] if order2 else None
    z = arb(0)
    # TF via the POLE-FREE difference series when x is in its design
    # regime (small x — the large-tau branch); else the per-gamma
    # Kummer route (JOURNAL gate catch #5)
    x1c_jet = cj * itj
    use_delta = bool((arb(float(np.max(d["src_te"]))) + cj.v).abs_upper()
                     * itj.v.abs_upper() < 0.01) and \
        bool(sj.v.abs_upper() < 0.5)
    gl_x1c = None if use_delta else gamma_low_jet(sj, x1c_jet, order2)
    # TF-block index map: jet vars (0,1,2) -> theta indices (3,4,5)
    JMAP = (3, 4, 5)
    HPAIRS3 = ((0, 0), (0, 1), (0, 2), (1, 1), (1, 2), (2, 2))
    for j in range(j0, j1):
        dm = arb(float(src_m[j]))        # already m - mc_min? no: m value
        dm = dm - d["mc_min_arb"]
        ts = float(src_ts[j])
        te = float(src_te[j])
        x2 = (arb(te) + cj) * itj
        x1 = x1c_jet if ts == 0.0 else (arb(ts) + cj) * itj
        if use_delta:
            TF = pref * delta_gamma_low_jet(sj, x1, x2, order2)
        else:
            gl2 = gamma_low_jet(sj, x2, order2)
            gl1 = gl_x1c if ts == 0.0 else gamma_low_jet(sj, x1, order2)
            TF = pref * (gl2 - gl1)
        # B = kappa * pi * D^-rho / rho ; log-linear pieces
        kap = k0 * (av * dm).exp()
        lnD = lnD_base + gm * dm
        Dmr = (-rho * lnD).exp()
        B = kap * piA * Dmr * irho
        Gv = B * TF.v
        val += Gv
        # dlogB over (lk0,a,ld,gam,rho) = (W, dm, -rho W, -rho dm,
        #                                  -lnD - 1/rho)
        dB = {1: W, 2: dm, 6: -rho * W, 7: -rho * dm, 8: -lnD - irho}
        for k, dv in dB.items():
            grad[k] += Gv * dv
        for m3 in range(3):
            grad[JMAP[m3]] += B * TF.g[m3]
        if order2:
            # hlogB nonzero: (6,8)=-W, (7,8)=-dm, (8,8)=irho^2
            hB = {(6, 8): -W, (7, 8): -dm, (8, 8): irho * irho}
            keys = sorted(dB.keys())
            for ii, k in enumerate(keys):
                for l in keys[ii:]:
                    e = dB[k] * dB[l]
                    hb = hB.get((k, l))
                    if hb is not None:
                        e = e + hb
                    hess[k][l] += Gv * e
            # TF second block
            for hidx, (m1, m2) in enumerate(HPAIRS3):
                hess[JMAP[m1]][JMAP[m2]] += B * TF.h[hidx]
            # cross dlogB x dTF
            for k, dv in dB.items():
                for m3 in range(3):
                    a_, b_ = sorted((k, JMAP[m3]))
                    hess[a_][b_] += dv * B * TF.g[m3]
    out = [ser(val)] + [ser(v) for v in grad]
    if order2:
        for k in range(9):
            for l in range(k, 9):
                out.append(ser(hess[k][l]))
    return out


def _init_worker(shared):
    _G.update(shared)


# ---------------------------------------------------------------------
class EtasOracle:
    """data: npz dict from etas_dump; part over the 9 theta coords."""

    def __init__(self, data, part, tag="", nworkers=10, prec=192):
        global LN10
        self.part = part
        self.tag = tag
        self.prec = prec
        self.nworkers = nworkers
        pt = np.asarray(data["pair_t"], np.int64)
        order = np.argsort(pt, kind="stable")
        self.pt = pt[order]
        self.ps = np.asarray(data["pair_s"], np.int64)[order]
        self.pdt = np.asarray(data["pair_dt"], float)[order]
        self.pr2 = np.asarray(data["pair_r2"], float)[order]
        pm = np.asarray(data["pair_m"], float)[order]
        self.mc_min = float(data["mc_min"])
        dmv = pm - self.mc_min
        bins, pbin = np.unique(np.round(dmv, 6), return_inverse=True)
        self.bins = bins
        self.pbin = pbin.astype(np.int32)
        self.n_t = int(len(data["trg_pbg"]))
        self.n_s = int(len(data["src_m"]))
        self.tptr = np.searchsorted(self.pt, np.arange(self.n_t + 1))
        self.src_m = np.asarray(data["src_m"], float)
        self.src_ts = np.asarray(data["src_ts"], float)
        self.src_te = np.asarray(data["src_te"], float)
        self.A = float(data["area"])
        self.T = float(data["tw_length"])
        self._pool = None
        LN10 = arb(10).log()

    @property
    def dims(self):
        return ([len(b) for b in self.part.blocks],
                len(self.part.border_idx))

    # ------------- box plumbing --------------------------------------
    def _theta_from_x(self, x):
        zs, g = x
        th = [None] * 9
        for bi, blk in enumerate(self.part.blocks):
            for pos, t in enumerate(blk):
                th[int(t)] = zs[bi][pos]
        for pos, t in enumerate(self.part.border_idx):
            th[int(t)] = g[pos]
        if any(v is None for v in th):
            raise OracleRefusal("partition", "part does not cover theta")
        return th

    def _shared(self):
        return dict(ps=self.ps, pt=self.pt, pdt=self.pdt, pr2=self.pr2,
                    pbin=self.pbin, tptr=self.tptr, bins=self.bins,
                    src_m=self.src_m, src_ts=self.src_ts,
                    src_te=self.src_te,
                    mc_min_arb=arb(self.mc_min))

    def _pool_get(self):
        import multiprocessing as mp
        if self._pool is None:
            ctxm = mp.get_context("fork")
            _init_worker(self._shared())     # also usable in-process
            self._pool = ctxm.Pool(self.nworkers)
        return self._pool

    def close(self):
        if self._pool is not None:
            self._pool.close()
            self._pool.join()
            self._pool = None

    def _eval(self, th, order):
        """(val, grad[9], hess[9][9] or None) — parallel over chunks."""
        th_ser = [ser(v) for v in th]
        prec = self.prec
        nw = self.nworkers
        # chunk targets by pair mass, sources evenly
        tb = np.linspace(0, self.n_t, 2 * nw + 1).astype(int)
        # balance: split by cumulative pairs
        cum = self.tptr
        total = cum[-1]
        marks = np.searchsorted(cum, np.linspace(0, total, 2 * nw + 1))
        marks[0] = 0
        marks[-1] = self.n_t
        marks = np.unique(marks)
        jobs = [( int(marks[i]), int(marks[i + 1]), th_ser, prec, order)
                for i in range(len(marks) - 1)]
        sb = np.linspace(0, self.n_s, nw + 1).astype(int)
        sjobs = [(int(sb[i]), int(sb[i + 1]), th_ser, prec, order)
                 for i in range(nw)]
        pool = self._pool_get()
        r1 = pool.map_async(_pairs_chunk, jobs)
        r2 = pool.map_async(_sources_chunk, sjobs)
        outs = r1.get() + r2.get()
        ctx.prec = prec
        val = arb(0)
        grad = [arb(0) for _ in range(9)]
        hess = [[arb(0)] * 9 for _ in range(9)] if order >= 2 else None
        for o in outs:
            val += deser(o[0])
            for k in range(9):
                grad[k] += deser(o[1 + k])
            if order >= 2:
                idx = 10
                for k in range(9):
                    for l in range(k, 9):
                        hess[k][l] += deser(o[idx])
                        idx += 1
        # mu * A * T term
        th_ = th
        W = arb(10).log()
        mu = (th_[0] * W).exp()
        AT = arb(self.A) * arb(self.T)
        val += mu * AT
        grad[0] += mu * W * AT
        if order >= 2:
            hess[0][0] += mu * W * W * AT
            for k in range(9):
                for l in range(k + 1, 9):
                    hess[l][k] = hess[k][l]
        if not val.is_finite():
            raise OracleRefusal("nonfinite_oracle", "value not finite")
        return val, grad, hess

    def sources_f64(self, th_float, order=2):
        """Float64 mids of the sources-side (sum G_j) value/grad/hess —
        the exact-register donor for the hybrid twin polish (no FD)."""
        ctx.prec = self.prec
        th = [arb(float(v)) for v in th_float]
        th_ser = [ser(v) for v in th]
        nw = self.nworkers
        sb = np.linspace(0, self.n_s, nw + 1).astype(int)
        sjobs = [(int(sb[i]), int(sb[i + 1]), th_ser, self.prec, order)
                 for i in range(nw)]
        pool = self._pool_get()
        outs = pool.map(_sources_chunk, sjobs)
        ctx.prec = self.prec
        val = 0.0
        grad = np.zeros(9)
        hess = np.zeros((9, 9)) if order >= 2 else None
        for o in outs:
            val += float(deser(o[0]).mid())
            for k in range(9):
                grad[k] += float(deser(o[1 + k]).mid())
            if order >= 2:
                idx = 10
                for k in range(9):
                    for l in range(k, 9):
                        hess[k][l] += float(deser(o[idx]).mid())
                        idx += 1
        if order >= 2:
            hess = np.triu(hess) + np.triu(hess, 1).T
        return val, grad, hess

    # ------------- engine-facing contract ----------------------------
    def nll(self, x):
        th = self._theta_from_x(x)
        v, _, _ = self._eval(th, 0)
        return v

    def _grad_full(self, x):
        th = self._theta_from_x(x)
        v, g, _ = self._eval(th, 1)
        return g, v

    def F(self, x):
        grad, _ = self._grad_full(x)
        Fz = [[grad[int(t)] for t in blk] for blk in self.part.blocks]
        Fg = [grad[int(t)] for t in self.part.border_idx]
        return Fz, Fg

    def F_full(self, x):
        return self.F(x)

    def H(self, x):
        from flint import arb_mat
        th = self._theta_from_x(x)
        _, _, Hfull = self._eval(th, 2)
        for a in range(9):
            for b in range(9):
                if not Hfull[a][b].is_finite():
                    raise OracleRefusal("nonfinite_oracle",
                                        f"H ({a},{b}) not finite")
        bi_ = self.part.border_idx
        D = []
        B = []
        for blk in self.part.blocks:
            D.append(arb_mat([[Hfull[int(s)][int(t)] for t in blk]
                              for s in blk]))
            B.append(arb_mat([[Hfull[int(s)][int(t)] for t in bi_]
                              for s in blk]))
        G = arb_mat([[Hfull[int(s)][int(t)] for t in bi_] for s in bi_])
        return D, B, G
