#!/usr/bin/env python3
"""
boundary.py — AMFlow-convention boundary values for eta-DE transport.

Normalization convention (pinned, see provenance below)
--------------------------------------------------------
All integrals use the AMFlow normalization:

    measure     prod_l  d^d k_l / (i pi^(d/2))      (one factor per loop)
    propagator  1 / (k^2 - m^2 + i0)^nu             (Minkowski, mostly-minus
                                                     irrelevant: only k^2 enters)
    d = 4 - 2*eps,  NO exp(eps*gammaE) / MSbar prefactor.

Under this convention the single-scale massive vacuum tadpole is

    T(nu; m^2, d) = (-1)^nu * Gamma(nu - d/2) / Gamma(nu) * (m^2)^(d/2 - nu)

so tadpole(m2=1, nu=1, d) = -Gamma(1 - d/2).

Provenance (how the convention was pinned)
------------------------------------------
* The AMFlow port (the AMFlow.cpp fork, the sibling repository amflow-cpp):
  src/qft/vacuum.cpp and
  include/amflow/qft/vacuum.hpp ("Mirrors AMFlow.m lines 819-824"): the
  (loops, props) = (1,1) builtin ending value is exactly -Gamma(eps - 1)
  = -Gamma(1 - d/2), i.e. tadpole(1, 1, d) above.  The full builtin
  single-mass vacuum table is ported verbatim in `singlemass_vacuum`.
* A triple-tadpole reference (a 60-digit fixture not shipped here):
  "T_def": "-Gamma(1-d/2)^3 ... measure d^dk/(i pi^(d/2)) per loop, m=1,
  no exp(eps gammaE)" with vendored 60d Laurent coefficients (eps^-3 -> 1.0,
  eps^-2 -> 3*(1-gammaE) = 1.26835300529...) verified to ~160d against the
  AMFlow oracle.  tests/test_boundary.py re-derives those coefficients from
  tadpole()^3 via epsfan.cauchy_laurent and gates them with gate.gate_strings.
* A production AMFlow run on a two-loop five-point family, with
  amf_options.ending_schemes = ["Tradition", "SingleMass"], d0 = 4,
  run_direction = "NegIm" (eta contour approaches infinity in the lower half
  plane).  The run artifacts confirm the scheme names and contour convention;
  the ending VALUE rules themselves are pinned from the port source:
  - AMFlow-port .../src/pipeline/amfsystem.cpp `try_builtin_ending_value`
    (~line 651): ending-system master with all indices <= 0  -> 1 (AMFlow
    bookkeeping convention, mirrored literally); all indices in {0,1} with
    (n_loops, n_props) in the vacuum table -> `qft::vacuum` closed form;
    anything else -> ending IBP reduction (`solve_ending_master_value`),
    which is OUT OF SCOPE here (raises NotImplementedError).
  - AMFlow-port .../src/pipeline/amfsystem.cpp `compute_single_mass_prefactor`
    (~line 2118):  prefactor = (-1)^n * Gamma(2-eps-m) * Gamma(-2+eps+m+n)
    / (Gamma(2-eps) * Gamma(n)),  m = m0 + m_eps_coef*eps,  and the GammaParams
    derivation (~line 3067):  m0 = total - n - 2*(loop_num-1),
    m_eps_coef = loop_num - 1  (total = sum of the master's indices on the
    component, n = index on the dropped massive line, loop_num = component
    loops).  Ported verbatim in `single_mass_prefactor`.

Which powers of eta are matched (Tradition ending, all-propagator eta mode)
---------------------------------------------------------------------------
With eta inserted into EVERY propagator (D_j -> D_j - eta), the eta -> inf
limit has a single non-scaleless region (all loop momenta hard, k ~ sqrt(eta)):

    I(nu_1..nu_P; eta) = eta^(L*d/2 - sum_j nu_j) * [ V(nu) + O(1/eta) ]

where V(nu) is the unit-mass vacuum integral of the same index pattern (the
`singlemass_vacuum` table for {0,1} patterns).  AMFlow matches ONLY the
boundary constant of that single leading power per master; every subleading
1/eta order is generated by the DE itself (calc_inf Taylor march), and all
other local exponents at infinity carry zero coefficient because their
regions are scaleless.  The sum runs over SIGNED indices (ISP numerators
nu < 0 raise the power).  Partial-eta insertion modes have multiple regions
with different powers and are NOT pinned here -> NotImplementedError.

Precision discipline: every function takes an explicit dps; all string
parsing happens inside `mp.workdps` (mpf import-dps footgun —
parsing high-precision strings at ambient mp.dps silently truncates).
Nothing here mutates global mp.dps.
"""

import mpmath as mp

__all__ = [
    "tadpole",
    "vacuum_known",
    "singlemass_vacuum",
    "single_mass_prefactor",
    "vacuum_ending_seed",
]


# ---------------------------------------------------------------------------
# parsing helper (import-dps footgun: only ever parse inside workdps)
# ---------------------------------------------------------------------------
def _mpnum(x):
    """Coerce int/str/mpf/mpc to a number AT THE CURRENT working precision.

    Must be called inside `with mp.workdps(...)`.  The unary `+` re-rounds
    already-parsed mpf/mpc into the current context.
    """
    if isinstance(x, (mp.mpf, mp.mpc)):
        return +x
    if isinstance(x, int):
        return mp.mpf(x)
    return mp.mpmathify(x)


def _pole_error(what, detail=""):
    return ValueError(
        what + " hit a Gamma pole" + ((" (%s)" % detail) if detail else "")
        + ".  This is the eps=0-exactly ill-posed case: the boundary "
        "constant carries an explicit 1/eps pole.  Use a small nonzero-eps "
        "grid and extrapolate (mirrors AMFlow-port amfsystem.cpp "
        "ending-master non-finite guard, ~line 1005).")


def _require_finite(val, what):
    bad = (mp.isnan(val.real) or mp.isinf(val.real)
           or mp.isnan(val.imag) or mp.isinf(val.imag))
    if bad:
        raise _pole_error(what, "non-finite value")


# ---------------------------------------------------------------------------
# tadpole
# ---------------------------------------------------------------------------
def tadpole(m2, nu, d, dps):
    """Single-scale massive vacuum tadpole, AMFlow normalization.

        T(nu; m^2, d) = (-1)^nu * Gamma(nu - d/2) / Gamma(nu) * (m^2)^(d/2-nu)

    Convention (STATED EXPLICITLY, pinned as per module docstring):
      * measure d^d k / (i pi^(d/2)) per loop,
      * propagator 1/(k^2 - m^2 + i0)^nu (Minkowski),
      * d = 4 - 2*eps, NO exp(eps*gammaE) factor.
    Matches AMFlow: tadpole(1, 1, d) = -Gamma(1 - d/2) = AMFlow-port
    qft::vacuum(1, 1) (AMFlow.m lines 819-824), and tadpole(1,1,d)^3 =
    T_def of the triple-tadpole reference (module docstring).

    Args:
      m2:  mass squared (int/str/mpf/mpc).  For complex or negative m2 the
           principal branch of (m2)^(d/2-nu) is used; the pinned reference
           case is real m2 > 0.
      nu:  integer propagator power >= 1 ((-1)^nu is branch-ambiguous
           otherwise; raise ValueError).
      d:   spacetime dimension (int/str/mpf/mpc), typically 4 - 2*eps.
      dps: target decimal precision of the returned value.

    Returns mpc, computed at dps+10 guard digits then rounded to dps.
    """
    if int(nu) != nu:
        raise ValueError("tadpole: nu must be an integer >= 1, got %r" % (nu,))
    nu = int(nu)
    if nu < 1:
        raise ValueError("tadpole: nu must be >= 1, got %d" % nu)
    with mp.workdps(dps + 10):
        m2v = _mpnum(m2)
        dv = _mpnum(d)
        try:
            val = mp.mpc((-1) ** nu) * mp.gamma(nu - dv / 2) / mp.gamma(nu)
            val = val * mp.power(mp.mpc(m2v), dv / 2 - nu)
        except ValueError as ex:   # mpmath raises on exact Gamma poles
            raise _pole_error("tadpole(m2=%r, nu=%d)" % (m2, nu), str(ex))
        val = mp.mpc(val)
        _require_finite(val, "tadpole(m2=%r, nu=%d)" % (m2, nu))
    with mp.workdps(dps):
        return +val


# ---------------------------------------------------------------------------
# single-mass vacuum table (AMFlow.m lines 819-824 via AMFlow-port vacuum.cpp)
# ---------------------------------------------------------------------------
# Entry: (loops, props) -> (sign, num_factors, den_factors) where each factor
# is (a, b, power) meaning Gamma(a*eps + b)^power.  Ported VERBATIM from
# src/qft/vacuum.cpp of the AMFlow.cpp fork (the sibling repository amflow-cpp).
# Attribution: these closed forms (and the prefactor in single_mass_prefactor)
# are AMFlow's — X. Liu, Y.-Q. Ma, arXiv:2201.11669; gitlab.com/multiloop-pku/amflow,
# MIT, (C) 2022 Xiao Liu, Yan-Qing Ma — as carried by AMFlow.cpp
# (github.com/chang18/amflow-cpp, MIT, (c) 2026 AMFlow.cpp contributors); the
# numbers are carried over, no source text is copied. See THIRD_PARTY.md B2.
_VACUUM_TABLE = {
    (1, 1): (-1, ((1, -1, 1),), ()),
    (2, 3): (-1, ((-1, 1, 2), (1, 0, 1), (2, -1, 1)), ((-1, 2, 1),)),
    (3, 4): (+1, ((-1, 1, 3), (2, -1, 1), (3, -2, 1)), ((-1, 2, 1),)),
    (3, 5): (-1, ((-3, 2, 1), (-1, 1, 4), (1, 0, 2), (3, -1, 1)),
             ((-2, 2, 2), (-1, 2, 1))),
    (4, 5): (-1, ((-1, 1, 4), (3, -2, 1), (4, -3, 1)), ((-1, 2, 1),)),
}


def vacuum_known(loops, props):
    """True iff (loops, props) is in the AMFlow builtin single-mass vacuum
    table (mirrors AMFlow-port qft::vacuum_known)."""
    return (int(loops), int(props)) in _VACUUM_TABLE


def singlemass_vacuum(loops, props, eps, dps):
    """Builtin single-mass vacuum integral value (AMFlow.m lines 819-824).

    The unit-mass vacuum integrals AMFlow uses as ending-system boundary
    values, for a master with all indices in {0,1} and `props` positive
    lines in an L=`loops` family.  Available (loops, props):
    (1,1) (2,3) (3,4) (3,5) (4,5).  d = 4 - 2*eps convention.

    Ported verbatim from src/qft/vacuum.cpp of the AMFlow.cpp fork
    (the sibling repository amflow-cpp; each factor is
    Gamma(a*eps + b)).  Raises ValueError on an unknown (loops, props)
    pair — mirrors qft::vacuum's invalid_argument.
    """
    key = (int(loops), int(props))
    if key not in _VACUUM_TABLE:
        raise ValueError(
            "singlemass_vacuum: unsupported (loops, props) = %r; known: %s"
            % (key, sorted(_VACUUM_TABLE)))
    sign, num, den = _VACUUM_TABLE[key]
    with mp.workdps(dps + 10):
        e = _mpnum(eps)
        try:
            val = mp.mpc(sign)
            for (a, b, p) in num:
                val *= mp.gamma(a * e + b) ** p
            for (a, b, p) in den:
                val /= mp.gamma(a * e + b) ** p
        except ValueError as ex:
            raise _pole_error("singlemass_vacuum(loops=%d, props=%d)" % key,
                              str(ex))
        val = mp.mpc(val)
        _require_finite(val, "singlemass_vacuum(loops=%d, props=%d)" % key)
    with mp.workdps(dps):
        return +val


# ---------------------------------------------------------------------------
# SingleMass loop-promotion prefactor
# ---------------------------------------------------------------------------
def single_mass_prefactor(n, m0, m_eps_coef, eps, dps):
    """SingleMass-scheme Gamma prefactor (AMFlow loop promotion).

        prefactor = (-1)^n * Gamma(2 - eps - m) * Gamma(-2 + eps + m + n)
                    / ( Gamma(2 - eps) * Gamma(n) ),
        m = m0 + m_eps_coef * eps          (note 2 - eps = d/2 at d = 4-2*eps)

    Ported verbatim from src/pipeline/amfsystem.cpp of the AMFlow.cpp fork
    (the sibling repository amflow-cpp), `compute_single_mass_prefactor`
    (~line 2118), which mirrors AMFSystemSetupMaster[..., "SingleMass"]
    (AMFlow.m lines 1039-1061).
    Parameter semantics (amfsystem.cpp ~line 3067):
      n           = index on the dropped massive propagator,
      m0          = total - n - 2*(loop_num - 1),
      m_eps_coef  = loop_num - 1,
    where total = sum of the master's indices on the component and loop_num
    = number of loops in the component.  Physically: the (loop_num-1)-loop
    massless sub-diagram scales as (-q^2)^(-m); the final q-integration
    against 1/(q^2 - 1)^n gives the Gamma ratio above (checked in
    tests/test_boundary.py: bubble x prefactor == singlemass_vacuum(2,3)).

    n must be a positive integer ((-1)^(-n) == (-1)^n in the C++ source).
    """
    if int(n) != n or int(n) < 1:
        raise ValueError("single_mass_prefactor: n must be integer >= 1, got %r" % (n,))
    n = int(n)
    with mp.workdps(dps + 10):
        e = _mpnum(eps)
        m = _mpnum(m0) + _mpnum(m_eps_coef) * e
        what = ("single_mass_prefactor(n=%d, m0=%r, m_eps_coef=%r)"
                % (n, m0, m_eps_coef))
        try:
            val = (mp.mpc((-1) ** n) * mp.gamma(2 - e - m)
                   * mp.gamma(-2 + e + m + n))
            val /= (mp.gamma(2 - e) * mp.gamma(n))
        except ValueError as ex:
            raise _pole_error(what, str(ex))
        val = mp.mpc(val)
        _require_finite(val, what)
    with mp.workdps(dps):
        return +val


# ---------------------------------------------------------------------------
# vacuum ending seed
# ---------------------------------------------------------------------------
def vacuum_ending_seed(desys, scheme, params, dps):
    """Large-eta boundary vector for AMFlow 'Tradition' / 'SingleMass' endings.

    Returns list[mpc] of length desys.n — the boundary constants c_i such
    that (Tradition, all-propagator eta mode, single hard region):

        I_i(eta) = c_i * eta^(L*(2-eps) - sum(nu_i)) * (1 + O(1/eta))
                                                       as eta -> infinity.

    ONLY the leading power per master is matched (see module docstring:
    "Which powers of eta are matched").  By default the eta-power is NOT
    applied (the transport/Frobenius layer owns the local exponents); pass
    params['eta'] to get c_i * eta^lambda_i evaluated at that eta (principal
    branch — AMFlow runs eta on the NegIm contour, the pinned run_direction
    convention; supplying eta on another sheet is on the caller).

    params (dict):
      'eps'          REQUIRED  epsilon value (str/mpf/mpc; d = 4 - 2*eps).
      'loops'        REQUIRED  int, loop count L of the ending family.
      'masters'      REQUIRED  list (len == desys.n, DE row order) of integer
                               index tuples of the ending-system masters.
      'eta'          optional  premultiply by eta^lambda_i (Tradition only).
      'gamma_params' SingleMass: list of (n, m0, m_eps_coef) per master.
      'sub_values'   SingleMass: list of the promoted sub-family master
                               values (one per master), solved upstream.
      'modes'        if present -> partial-eta insertion -> NotImplementedError.

    Per-master value rule, mirroring AMFlow-port amfsystem.cpp
    `try_builtin_ending_value` (~line 651) literally:
      * all indices <= 0                          -> 1   (bookkeeping conv.)
      * all indices in {0,1}, P = #ones >= 1, and
        (L, P) in the vacuum table                -> singlemass_vacuum(L, P)
      * anything else -> NotImplementedError: needs the ending IBP reduction
        (`solve_ending_master_value` analogue).  Not supported here: it would
        need Kira reduction rules wired through de_load.load_kira_targets and
        back-substituted to the table masters exactly as amfsystem.cpp does.

    SingleMass scheme: seed_i = single_mass_prefactor(*gamma_params[i]) *
    sub_values[i]  (mirrors sm_cfg_ application, amfsystem.cpp ~line 2324).
    If gamma_params/sub_values are missing -> NotImplementedError: deriving
    them needs FactorizeFamily + the promoted-leg sub-family solve, which is
    not pinnable from the run artifacts alone.  Not supported here: it would
    need a port of FactorizeFamily (amfsystem.cpp single_mass_setup_master,
    ~line 2812) and a transport solve of the (loop_num-1)-loop sub-family,
    fed in as 'sub_values'.
    SingleMass endings carry no eta ('eta' in params -> ValueError).
    """
    n_sys = int(getattr(desys, "n"))
    if not isinstance(params, dict):
        raise ValueError("vacuum_ending_seed: params must be a dict")
    if "modes" in params:
        raise NotImplementedError(
            "vacuum_ending_seed: partial-eta insertion modes have multiple "
            "large-eta regions with distinct powers; only the all-propagator "
            "single-hard-region case is pinned.  Not supported: the region/"
            "RegionPower machinery (amflow-cpp qft::find_all_region + "
            "build_boundary, amfsystem.cpp ~line 1403) is not ported.")
    for req in ("eps", "loops", "masters"):
        if req not in params:
            raise ValueError("vacuum_ending_seed: params[%r] is required" % req)
    masters = params["masters"]
    if len(masters) != n_sys:
        raise ValueError(
            "vacuum_ending_seed: len(masters)=%d != desys.n=%d"
            % (len(masters), n_sys))
    loops = int(params["loops"])

    if scheme == "Tradition":
        seeds = []
        for i, idx in enumerate(masters):
            idx = [int(v) for v in idx]
            if all(v <= 0 for v in idx):
                with mp.workdps(dps):
                    seeds.append(mp.mpc(1))
                continue
            if all(v in (0, 1) for v in idx):
                p = sum(idx)
                if vacuum_known(loops, p):
                    # NOTE: no mp.mpc() wrapper here — converting at ambient
                    # precision would silently truncate to mp.dps (the same
                    # class of bug as the import-dps footgun).
                    seeds.append(
                        singlemass_vacuum(loops, p, params["eps"], dps))
                    continue
                raise NotImplementedError(
                    "vacuum_ending_seed: master %d %r -> (loops=%d, props=%d) "
                    "not in the builtin vacuum table %s.  Not supported: ending IBP "
                    "reduction to table masters (amfsystem.cpp "
                    "solve_ending_master_value) through "
                    "de_load.load_kira_targets reduction rules."
                    % (i, idx, loops, p, sorted(_VACUUM_TABLE)))
            raise NotImplementedError(
                "vacuum_ending_seed: master %d %r has indices outside {0,1} "
                "with a positive line; value requires the ending IBP "
                "reduction (amfsystem.cpp solve_ending_master_value), which is "
                "not supported here."
                % (i, idx))
    elif scheme == "SingleMass":
        if "eta" in params:
            raise ValueError(
                "vacuum_ending_seed: SingleMass endings carry no eta (the "
                "scheme fires on families already of single-mass vacuum "
                "shape; amfsystem.cpp single_mass_ending_q_impl).")
        gp = params.get("gamma_params")
        sv = params.get("sub_values")
        if gp is None or sv is None:
            raise NotImplementedError(
                "vacuum_ending_seed(SingleMass): params['gamma_params'] and "
                "params['sub_values'] are required.  Deriving them needs "
                "FactorizeFamily + the promoted-leg sub-family solve "
                "(amfsystem.cpp single_mass_setup_master ~line 2812), not "
                "pinnable from run artifacts alone.  Not supported without them: "
                "solve the (loop_num-1)-loop sub-family by "
                "transport and pass its master values as 'sub_values'.")
        if len(gp) != n_sys or len(sv) != n_sys:
            raise ValueError(
                "vacuum_ending_seed(SingleMass): gamma_params/sub_values must "
                "have length desys.n=%d" % n_sys)
        seeds = []
        for i in range(n_sys):
            n_i, m0_i, mec_i = gp[i]
            pref = single_mass_prefactor(n_i, m0_i, mec_i, params["eps"], dps)
            with mp.workdps(dps + 10):
                seeds.append(mp.mpc(pref) * _mpnum(sv[i]))
    else:
        raise ValueError(
            "vacuum_ending_seed: unknown scheme %r (pinned: 'Tradition', "
            "'SingleMass'; the AMFlow amf_options.ending_schemes "
            "values)" % (scheme,))

    if scheme == "Tradition" and "eta" in params:
        with mp.workdps(dps + 10):
            e = _mpnum(params["eps"])
            eta = _mpnum(params["eta"])
            out = []
            for i, idx in enumerate(masters):
                lam = loops * (2 - e) - sum(int(v) for v in idx)
                out.append(mp.mpc(seeds[i]) * mp.power(mp.mpc(eta), lam))
            seeds = out

    with mp.workdps(dps):
        return [+mp.mpc(s) for s in seeds]
