#!/usr/bin/env python3
# lockpick bilmine member (F1 ring stage) — close-out driver (script-generated MANIFEST_SHA256.txt, optional producer lint, close stamp).
"""close_leg_f1.py — BILMINE-F1 close-out: MANIFEST_SHA256.txt
(script-generated), optional producer lint (line captured to
work/LINT_LINE.txt), close stamp."""
import hashlib, os, subprocess, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from bilmine_f1_lib import leg_dir_f1  # noqa: E402


def main():
    LEG = leg_dir_f1()
    LINT = os.environ.get("BILMINE_PRODUCER_LINT")  # optional
    lines = []
    for root, _dirs, files in os.walk(LEG):
        if "__pycache__" in root:
            continue
        for f in sorted(files):
            if f in ("MANIFEST_SHA256.txt", "STAMP_DONE.txt",
                     "LINT_LINE.txt"):
                # LINT_LINE.txt is (re)written AFTER the manifest walk on
                # every close, so it is excluded like the stamp — the parent
                # leg's manifest likewise never contained it (single close,
                # file created post-walk).
                continue
            p = os.path.join(root, f)
            h = hashlib.sha256(open(p, "rb").read()).hexdigest()
            lines.append(f"{h}  {os.path.relpath(p, LEG)}")
    stamp = subprocess.check_output(["date", "-u"]).decode().strip()
    with open(f"{LEG}/MANIFEST_SHA256.txt", "w") as fh:
        fh.write("# BILMINE-F1 manifest — script-generated by "
                 "close_leg_f1.py at " + stamp + " (date -u)\n")
        fh.write("\n".join(sorted(lines)) + "\n")
    rc = 0
    if LINT:
        r = subprocess.run([sys.executable, LINT, LEG], capture_output=True,
                           text=True)
        line = (r.stdout.strip().splitlines() or [""])[-1]
        open(f"{LEG}/work/LINT_LINE.txt", "w").write(
            line + "\n(rc=%d; producer_lint at close, %s)\n"
            % (r.returncode, stamp))
        print("LINT:", line, "rc=", r.returncode)
        rc = r.returncode
    with open(f"{LEG}/STAMP_DONE.txt", "w") as fh:
        fh.write(stamp + "\n")
    print("CLOSED", stamp)
    return rc


if __name__ == "__main__":
    sys.exit(main())
